### ISSUE TITLE
Support parallel builds with GC3Pie

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-framework#1006]
This is to track activity on the GC3Pie job backend, as per *CONTRIBUTING.md* guidelines.

I'm keeping in-development code at: https://github.com/gc3-uzh-ch/easybuild-framework/tree/gc3pie

**Comment by boegel** [comment]
@riccardomurri: let's close this issue, since things are being followed up in #1008?

**Comment by riccardomurri** [comment]
Sure. :-)
