### ISSUE TITLE
Ability to override paths

### ISSUE THREAD

**Issue by ahmedsajid** [hpcugent/easybuild-framework#1013]
Hi,

It would be great if there was parameter override default paths such as LD_LIBRARY_PATH in easybuild generated modulefiles from using easyconfig file rather than creating a separate easyblock.

Ahmed.

**Comment by boegel** [comment]
@ahmedsajid No longer relevant to you? Can you clarify?

**Comment by ahmedsajid** [comment]
@boegel no longer using easybuild.
Completely forgot what this was about.
