### ISSUE TITLE
--from-pr fails to find already available patch files

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#1140]
Patch files are only looked for at i) next to the easyconfig file being used, ii) next to the source tarball.

For pull requests in which an already available patch file is used, it's possible the patch is not found since the used easyconfigs are downloaded from the PR to `/tmp/...`

@gjbex was hit by this issue in https://github.com/hpcugent/easybuild-easyconfigs/pull/1308

**Comment by boegel** [comment]
@fgeorgatos: I seem to remember another instance of this issue occurring with you. Do you recall the details (which PR was being tested)?

**Comment by fgeorgatos** [comment]
@boegel: #1138 ?
Στις 17 Ιαν 2015 1:05 ΠΜ, ο χρήστης "Kenneth Hoste" <
notifications@github.com> έγραψε:

**Comment by fgeorgatos** [comment]
Or... #1141
Στις 17 Ιαν 2015 2:33 ΠΜ, ο χρήστης "Fotis Georgatos" <kefalonia@gmail.com>
έγραψε:

**Comment by boegel** [comment]
@fgeorgatos: yes, it was https://github.com/hpcugent/easybuild-easyconfigs/pull/1141, thanks!

**Comment by fgeorgatos** [comment]
btw. I just notice that framework and easyconfigs PR numbers are up to par (=about the same).
This is seriously confusing, esp. for/from guys like me who bother not to mention or look at the repo ;-)
Do we have any easy way out or is it a "live with it" situation? Yeah, I know, PEBCAK...

**Comment by boegel** [comment]
@fgeorgatos: there's nothing much that can be done about this, but usually there's a clear separation between framework and easyconfig issues, right?

**Comment by fgeorgatos** [comment]
OK. Let's say yes for the moment (ie. "leave as-is") and take a note it may
bug us...

On Mon, Jan 19, 2015 at 3:39 PM, Kenneth Hoste <notifications@github.com>
wrote:

> @fgeorgatos <https://github.com/fgeorgatos>: there's nothing much that
> can be done about this, but usually there's a clear separation between
> framework and easyconfig issues, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-framework/issues/1140#issuecomment-70493277>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by boegel** [comment]
It seems like @gjbex ran into this because the `easybuild-easyconfigs` directory was not included in `$PYTHONPATH`, nor in the default robot search path (via either `robot` or `robot-paths`), which explains why the patch file could not be found; both paths are also consider when trying to locate patch files, next to the source paths and the location of the easyconfig file.

To be confirmed via https://github.com/hpcugent/easybuild-easyconfigs/pull/1330/.

**Comment by boegel** [comment]
So, as shown in https://github.com/hpcugent/easybuild-easyconfigs/pull/1330, `--from-pr` is not broken, this is a configuration issue: the easyconfigs (and patches) that come installed with EasyBuild are not available, hence the patch files can not be located.

Closing this.
