### ISSUE TITLE
tests do not complete successfully

### ISSUE THREAD

**Issue by jbbernar** [hpcugent/easybuild-framework#1175]
I've installed easybuild, using the bootstrap method, using Lmod 5.9 (to be precise, 5.9-5-g3504ca2, git cloned today), on a newly installed RHEL 6.6 system. The install seemed to work, but the post-install tests fail.

$ eb --version
This is EasyBuild 1.16.1 (framework: 1.16.1, easyblocks: 1.16.1) on host bbpca034.
/home/jbernard/.local/easybuild/software/EasyBuild/1.16.1/lib/python2.6/site-packages/easybuild_framework-1.16.1-py2.6.egg/vsc/utils/generaloption.py:1031: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  msg = err.message

$ module --version
Modules based on Lua: Version 5.9 (5.9-5-g3504ca2) 2015-02-10 05:36
    by Robert McLay mclay@tacc.utexas.edu

A gist of the test output is here: https://gist.github.com/a483bba78e03b5be04e6.git.

I'm happy to provide any addtional info.

**Comment by boegel** [comment]
Thanks for sharing the output of the tests. We're already aware that some of the tests need work to make them more robust, see also https://github.com/hpcugent/easybuild-framework/pull/1167 .

I'll take a detailed look at the tests that are failing for you, and get back to me (do ping me if you don't hear back from me).

I suspect it's an issue specific to the tests themselves, but if you notice any problems with using EasyBuild, please report those issues too.

**Comment by boegel** [comment]
#1167 has been merged, the tests should now be a lot more robust (in the `develop` branch)

There are a couple of issues that pop up in your test output though, most notably this:

```
patch: command not found
```

That's external to EasyBuild, I guess that should be listed as an external dependency...

@jbbernar: Up for giving the tests another try once EasyBuild v2.0 is released (should happen in the next 2 weeks or so).

**Comment by jbbernar** [comment]
Sure, I'll watch for the announcement.

**Comment by boegel** [comment]
I'll close this for now, feel free to reopen in case you run into broken tests with v2.0.
