### ISSUE TITLE
#installation-of-latest-development-version recipe adjustments needed for Lmod

### ISSUE THREAD

**Issue by malcook** [hpcugent/easybuild-framework#1203]
Following http://easybuild.readthedocs.org/en/latest/Installation_Alternative.html#installation-of-latest-development-version in pure Lmod environment

This step fails:

```
module load $HOME/EasyBuild/$$/module-EasyBuild-develop
```

But succeeds when split, as:
```
module use  $HOME/EasyBuild
module load module-EasyBuild-develop
```

When I made this observation in an email, @boegel replied:

> Lmod does indeed not support loading module files 'full path' style...
> So the script to set up develop assumes the use of Tcl/C environment modules.

Perhaps this assumption should NOT be made?

**Comment by boegel** [comment]
In the development version of the documentation for this script, this has been fixed, see http://easybuild.readthedocs.org/en/develop/Installation_Alternative.html#installation-of-latest-development-version .

Does that resolve the problems? If so, please close this issue.

**Comment by malcook** [comment]
Not quite.  

The wiki doc looks good in this respect, but the updated script now prompts:
```
=== Run 'module load /tmp/n/opt/EasyBuild-JUxjUj/module-EasyBuild-develop' to use your development version of EasyBuild.
=== (you can add a symlink in your MODULEPATH to make this module appear together with the others)
```

Also, this script for me does NOT work when I specify my own github account.  I must specify hpcugent.  Thereupon, it prompts me 10 times for my passphrase.  This can not be what you intended.  Please advise!

**Comment by malcook** [comment]
Fix confirmed now - the wiki and the message now agree - also I had been failing to first clone the repos on github.
