### ISSUE TITLE
easybuild-wiki dependency unclear in "Installation of latest development version using provided script"

### ISSUE THREAD

**Issue by malcook** [hpcugent/easybuild-framework#1213]
The recipe provided for "Installation of latest development version using provided script"
- should name the the easybuild repositories required
- including the wiki

since:
```
# Clone wiki repository with the 'master' branch
github_clone_branch "easybuild-wiki" "master"
```
is part of install-EasyBuild-develop.sh

**Comment by boegel** [comment]
fixed in https://github.com/hpcugent/easybuild/pull/108
