### ISSUE TITLE
why a bare repo?

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1235]
Hi 

I have been trying to get working the option "repository=GitRepository" without luck. Probably because I am not used to git bare repos. could anyone detail the right procedure to get this working? 

In any case, by now I will stay using flat files because I don't like the idea of having my easyconfigs inside a bare repo and not being able to browse/edit them. Or am I missing something?

@JensTimmerman @boegel mentions you added this feature? any comments on this?

**Comment by JensTimmerman** [comment]
I initially added some git stuff, but much was rewritten since then :-)

Can you please send me the errors you're getting so I can see what the issue is?

first of all, is GitRepository in your choices if you run `eb --help` ?

**Comment by pescobar** [comment]
this is what I get when doing "eb --help"

```
   --repository=REPOSITORY
                        Repository type, using repositorypath (type choice;
                        def FileRepository) (choices: FileRepository,
                        GitRepository)
```

This is the error I get when trying to use it:

```
mkdir /tmp/bare

cd /tmp/bare/

git init --bare
Initialized empty Git repository in /tmp/bare/

eb --modules-tool=Lmod --sourcepath=/export/bc2_gp/soft/source  --repository=GitRepository --repositorypath=/tmp/bare Java-1.7.0_15.eb --debug -f
== temporary log file in case of crash /tmp/eb-PnIldq/easybuild-vU_0eh.log
== processing EasyBuild easyconfig /tmp/eb-tmp/easybuild/easyconfigs/j/Java/Java-1.7.0_15.eb
== building and installing Java/1.7.0_15...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== packaging...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== COMPLETED: Installation ended successfully
== Results of the build can be found in the log file /import/bc2/home/admin/soft/.local/easybuild/software/Java/1.7.0_15/easybuild/easybuild-Java-1.7.0_15-20150324.163810.log
ERROR: EasyBuild encountered an exception (at easybuild/tools/repository/gitrepo.py:123 in create_working_copy): pull in working copy /tmp/eb-PnIldq/git-wc-uQeg_C/bare went wrong: 'git pull' returned exit status 1: Your configuration specifies to merge with the ref 'master'
from the remote, but no such ref was fetched.
```

here you have the complete debug log:
https://gist.github.com/4396b3c737e7ca7733bd

**Comment by JensTimmerman** [comment]
ok, the bare repository also needs an initial commit to a master branch, as the documentation here states: http://easybuild.readthedocs.org/en/latest/Configuration.html 
` a non-empty bare` repository. 
So I think the `git init --bare` in the documentation is confusing, because you still need to then clone the repo, add a branch, and push the branch to the repository.

**Comment by pescobar** [comment]
ok, I managed to get this working and even push directly to my local gitlab. Thanks for this nice feature @JensTimmerman   :)

**Comment by boegel** [comment]
So, is there a good reason to stick with a bare repo? @JensTimmerman?

Or should we also consider supporting a non-bare git repo for archiving easyconfigs?

@pescobar: up for documenting the steps you had to take, and integrate it in http://easybuild.readthedocs.org?

**Comment by pescobar** [comment]
I think bare repo is the best option because the repos hosted in gitlab or github are bare repos.

the only detail is that the repo cannot be empty, basically if you create the bare repo (create the repo in gitlab or github works) clone it, add some files, commit and push and then you can save your installed easyconfigs to your repo url just doing 

```
eb --repository=GitRepository --repositorypath=git@gilab-url.com:easybuild/installed_easyconfigs.git
```

**Comment by JensTimmerman** [comment]
It's recommended to never push to a non bare repo.

**Comment by pescobar** [comment]
@JensTimmerman I have just submit this PR about this topic

https://github.com/hpcugent/easybuild-framework/pull/1243
