### ISSUE TITLE
incomplete build logs 

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1237]
for some easyconfigs like R with many extensions the build log is too long and easybuild doesn't keep the complete build log in the installation directory.  More details here:
https://github.com/hpcugent/easybuild-easyconfigs/pull/1497#issuecomment-85207675

**Comment by boegel** [comment]
fixed with #1238, closing this (discussion should continue in #1238)

thanks for reporting this @pescobar!
