### ISSUE TITLE
easybuild not checking the existence of the configuration file

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1239]
This is a minor problem but when I try to use a non-existent easybuild configuration file the error doesn't say "config file not found". Easybuild just tries to run with the default parameters and as I use Lmod it complains about not finding EnvironmentModulesC

It would be nice if the error message is "config file /tmp/asdfasdfasdf not found"

```
[soft@compilator ~]$ eb --configfiles=/tmp/asdfasdfasdf
== temporary log file in case of crash /tmp/eb-kisXvE/easybuild-owPmud.log
ERROR: EasyBuild crashed with an error (at easybuild/tools/modules.py:231 in check_cmd_avail): EnvironmentModulesC modules tool can not be used, 'modulecmd' command is not available.
```

**Comment by boegel** [comment]
@stdweird: thoughts? This is not good behaviour imho, `eb` should indeed be complaining that the specified config file isn't around?

**Comment by stdweird** [comment]
hmm, i'm a bit surprised by this. will check generaloption to make this configurable if need be

**Comment by boegel** [comment]
why make it configurable? specifying a non-existing config file is wrong, and you should be made aware?

**Comment by stdweird** [comment]
https://github.com/hpcugent/vsc-base/blob/master/lib/vsc/utils/generaloption.py#L1108
so you can set it to True in EB

**Comment by boegel** [comment]
OK, I'll look into that...

This will be tricky w.r.t. default config file locations, I think...

**Comment by boegel** [comment]
see #1240, just a little bit tricky w.r.t. config unit tests (closing this, let's follow up in the PR)

**Comment by boegel** [comment]
Thanks for reporting this @pescobar!
