### ISSUE TITLE
Compilation hanging of custom easyblock h5py with python3 (CrayGNU toolchain)

### ISSUE THREAD

**Issue by gppezzi** [hpcugent/easybuild-framework#1313]
This problem is related to the mpi4py issue #1312 and I'm using a custom easyblock that extends PythonPackage, here are the related files:

https://github.com/eth-cscs/tools/blob/master/easybuild/easyblocks/h5py.py
https://github.com/eth-cscs/tools/blob/master/easybuild/easyconfigs/h/h5py/h5py-2.5.0-CrayGNU-5.2.40-Python-3.4.3-parallel.eb
https://github.com/eth-cscs/tools/blob/master/easybuild/easyconfigs/p/Python/Python-3.4.3-CrayGNU-5.2.40.eb

This build gets stuck at some loop during the configuration step, I still don't have details on that but @boegel mentioned that he sees an MPI_init error when running it interactively. 

I will try to give more details soon.

**Comment by gppezzi** [comment]
Problem has been fixed by removing the python3 easyconfig line that modifies the PYTHONPATH for the extensions: 

exts_filter = ('PYTHONPATH="%(installdir)s:$PYTHONPATH python -c "import %(ext_name)s"', '')

This line came from Python-3.4.3-intel-2015a.eb (EB 2.1.1), I suppose this was used for a custom install but I think that for a stock eb file it can be misleading to propagate current PYTHONPATH to a fresh python installation.

**Comment by boegel** [comment]
Thanks for the update @gppezzi !
