### ISSUE TITLE
Bug in packaging, module_generator in fake state before packaging

### ISSUE THREAD

**Issue by rjeschmi** [hpcugent/easybuild-framework#1329]
We missed the module path in testing the package feature and it is accidentally left in the "fake" state before the package step runs.

I'm looking into a PR for this, but it isn't trivial since the state isn't isolated (sanity check step seems to rely on the state already being fake for module_generator).

**Comment by rjeschmi** [comment]
reported by @dirkdedraak

**Comment by boegel** [comment]
fix available in #1348, let's continue the discussion there
