### ISSUE TITLE
Bootstrap failure on CentOS 7.1

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-framework#1347]
Hello

I'm trying out EasyBuild on a CentOS 7.1. instance on OpenStack, using the bootstrapping script as suggested at http://easybuild.readthedocs.org/en/latest/Installation.html

I have installed Lmod but see the following error:

[centos@easybuild-1 ~]$ sh ~/tmp/bootstrap-easybuild.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30044  100 30044    0     0  49294      0 --:--:-- --:--:-- --:--:-- 49252
[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl
Check the output of 'type module' to determine the location of the module command you are using.
Lmod has detected the following error:  The following module(s) are unknown: "EasyBuild"

   Please check the spelling or version number. Also try "module spider ..."

[centos@easybuild-1 ~]$ type module
module is a function
module ()
{
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

[centos@easybuild-1 ~]$ module --version

Modules based on Lua: Version 5.9.4.2  2015-05-18 16:35
    by Robert McLay mclay@tacc.utexas.edu

[centos@easybuild-1 ~]$ module spider

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
The following is a list of the modules currently available:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  lmod: lmod/5.9.4.2
    Lmod: An Environment Module System

  settarg: settarg/5.9.4.2

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
To learn more about a package enter:

   $ module spider Foo

where "Foo" is the name of a module

To find detailed information about a particular package you
must enter the version if there is more than one version:

   $ module spider Foo/11.1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by boegel** [comment]
Do you have `lmod` available in `$PATH`? See the note in http://easybuild.readthedocs.org/en/latest/Installation.html#required-modules-tool

**Comment by verdurin** [comment]
Must admit I didn't pay too much attention because I assumed the Lmod RPM would take care of that, but it appears not.

I've now added a symbolic link to /usr/share/lmod/lmod/libexec/lmod in ~/.local/bin but I see the same failure.

**Comment by boegel** [comment]
Well, the error message must be different now? Are you still seeing `[[ERROR]] Could not find any module command, make sure one available in your $PATH.` ?

**Comment by verdurin** [comment]
No, it's the same:

[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl

**Comment by verdurin** [comment]
Okay, the symbolic link was failing. It does work if I explicitly add /usr/share/lmod/lmod/libexec to $PATH. 

I think the instructions should be clarified here, because it's rather unexpected that installing the Lmod RPM wouldn't be sufficient in itself. Unless it's just me...

**Comment by boegel** [comment]
Well, having `lmod` available via `$PATH` isn't standard, it typically isn't needed since `lmod` is not used directly (people interact via `module` or `ml`).

EasyBuild needs direct access to the actual binary itself though, since it asks `lmod` to produce output in Python syntax (rather than `bash` commands).

We may be able to enhance EasyBuild to get rid of this requirement though, by parsing the output of `type module` and trying to figure out the full path to the actual `lmod` binary ourselves.

Not sure if it's worth the trouble though...

**Comment by verdurin** [comment]
I think reinforcing the point in the instructions that (in this case) installing the Lmod package on its own is not sufficient would be enough.

**Comment by verdurin** [comment]
@boegel - can we find some method of dealing with this? Just been bitten by it again, and annoyed by it again...

**Comment by boegel** [comment]
@verdurin: if we can't find `modulecmd` or `lmod` via `$PATH`, we can try and figure it out ourselves through `type -f module` as a desperate attempt... But somehow will have to implement that. :-)

**Comment by verdurin** [comment]
It gets a lot further if I set:
`export EASYBUILD_MODULES_TOOL=Lmod`

but then I see an error at the end:

```
INFO: Processing dependencies for vsc-base
INFO: Finished processing dependencies for vsc-base
[[INFO]]

+++ STAGE 2: installing EasyBuild in /srv/data/sw/eb with EasyBuild from stage 1...


Traceback (most recent call last):
  File "./bootstrap_eb.py", line 750, in <module>
    main()
  File "./bootstrap_eb.py", line 560, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "./bootstrap_eb.py", line 478, in stage2
    easybuild_main()
  File "/tmp/tmpact6eZ/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/easybuild/main.py", line 167, in main
    eb_go = eboptions.parse_options(args=args)
  File "/tmp/tmpact6eZ/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/easybuild/tools/options.py", line 897, in parse_options
    raise EasyBuildError("Failed to parse configuration options: %s" % err)
easybuild.tools.build_log.EasyBuildError: 'Failed to parse configuration options: parseconfigfiles: configfile /srv/data/sw/eb/apps/EasyBuild/easybuild.cfg not found.'
```

**Comment by verdurin** [comment]
Okay, that was spurious.

Setting the modules tool before running bootstrap appears to be sufficient, when using Lmod from EPEL on CentOS 7.2. At least that's less ugly than messing with $PATH.

**Comment by boegel** [comment]
@verdurin: that's because for Lmod we also take`$LMOD_CMD` into account

**Comment by verdurin** [comment]
Yes, I know - that's why I tried it...

Could this be added to the documentation? Happy to do so myself.

**Comment by boegel** [comment]
@verdurin: http://easybuild.readthedocs.org/en/latest/Installation.html?highlight=LMOD_CMD#required-modules-tool

**Comment by verdurin** [comment]
@boegel - yes, I know about that, and that variable is set by the EPEL RPM. The point is that this is not sufficient. Unless I set EASYBUILD_MODULES_TOOL as well, it fails.

**Comment by boegel** [comment]
@verdurin: we should close this as duplicate of #1500?

**Comment by verdurin** [comment]
Agreed. Closed.
