### ISSUE TITLE
Dash not prepended to versionsuffix

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-framework#1352]
The [documentation](http://easybuild.readthedocs.org/en/latest/Writing_easyconfig_files.html) says that an easyconfig file is in the format
```
<name>-<version>[-<toolchain>][-<versionsuffix>].eb.
```
but actually a ```-``` is not prepended to versionsuffix, if you want one you have to add it by hand (e.g., see [here](https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/n/netCDF-C%2B%2B/netCDF-C%2B%2B-4.2-ictce-4.1.13-mt.eb))

**Comment by boegel** [comment]
This is an oversight in the documentation, not the code.

Not automagically prepending a `-` provides more freedom, e.g. to use another character (or none) to separate `versionsuffix`.

**Comment by boegel** [comment]
Fixed with https://github.com/hpcugent/easybuild/commit/63aec2d36724215d6978445ca24e59ad834d720d, thanks @ocaisa

**Comment by boegel** [comment]
and also https://github.com/hpcugent/easybuild/commit/f9c9917e1a82d43fa3eaba197cdff97bcc4c8d63
