### ISSUE TITLE
Feature request to add a configuration option like --cleanup-tmpdir

### ISSUE THREAD

**Issue by Louwrensth** [hpcugent/easybuild-framework#1362]
I’m playing around with EB and I would like to know if there is an option to keep the temporary logs and directory when using the `--try` and `--dry-run` options. I would like to inspect the tweaked easyconfig files that were generated.

Right now, the removal of the temporary directory is hardcoded.

But, it shouldn't be too hard to add a configuration option like `--cleanup-tmpdir`, which is True by default and is equivalent to `--cleanup-builddir` which we already have.

**Comment by boegel** [comment]
WIP pull request @ https://github.com/hpcugent/easybuild-framework/pull/1365, let's follow this up there

Thanks for bringing this up @Louwrensth!
