### ISSUE TITLE
Replace dot "." with underscore in environment variables for software with "." in his name 

### ISSUE THREAD

**Issue by jas02** [hpcugent/easybuild-framework#1391]
In case that I am building software that contains "." in name like MPI.NET, there is problem with loading such a module, because environment modules can't contain dot in the name of variable.

**Comment by boegel** [comment]
To be more specific: the generated module file tries to define an environment variable named `EBDEVELMPI.NET`, which fails.

**Comment by wpoely86** [comment]
Fix in #1538

**Comment by boegel** [comment]
let's follow-up in #1538
