### ISSUE TITLE
Intel Ifort and FC compiler variable

### ISSUE THREAD

**Issue by DirkdeDraak** [hpcugent/easybuild-framework#1392]
On 15/09/15 14:10, Kenneth Hoste  wrote:
My guess is that the reason that the framework currently doesn't define $FC is because it's unclear whether $FC should be set to the value used in $F77 or $F90... 

This is mostly historic though, since I think $F77 and $F90 are now set to the same value for all Fortran compilers we support. 

Maybe open an issue for this via https://github.com/hpcugent/easybuild-framework/issues/new, just so it doesn't get forgotten easily? 

It's a trivial change to also define $FC, but I fear it may come with some fallout (some builds may suddenly start failing with having $FC defined). 

Making a change like this early in the development phase of the next EB version makes sense, since it's likely we'll pick up any issues caused by it well before the 2.4.0 release. 

regards,

Kenneth

On 15/09/15 14:10, Fokko Masselink wrote:
Hi,

I'm building OpenMPI 1.10.0 with EasyBuild against an Intel Toolchain with GCC
4.9.2.
In the configure step gfortran is used as the Fortran compiler, though we want
to use ifort from Intel of course.
Turns out (if I'm not mistaken) that the configure of OpenMPI looks for the FC
environment variable and ignores both F77 and F90.
Can the FC variable be included in the compiler toolchains?

Now I overcome this by adding
preconfigopts = 'FC=$F90 CFLAGS="%s" CXXFLAGS="%s" FCFLAGS="%s" ' % (....)
to the easyconfig file

A very basic manual test also shows this behavior:
$ untar OpenMPI tarball
$ module load intel
$ CC=icc CXX=icpc F90=ifort ./configure
*** Fortran compiler
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking whether ln -s works... yes
checking if Fortran compiler works... yes

Once you start to specify intel specific FCFLAGS the gfortran compiler will
fail to build software and the configure process is stopped.

If you configure with the following:
$ untar OpenMPI tarball
$ module load intel
$ CC=icc CXX=icpc FC=ifort ./configure
*** Fortran compiler
checking whether we are using the GNU Fortran compiler... no
checking whether ifort accepts -g... yes
checking whether ln -s works... yes
checking if Fortran compiler works... yes

**Comment by boegel** [comment]
fixed with #1394, let's follow up there
