### ISSUE TITLE
Extension: wrong sources and patches default value

### ISSUE THREAD

**Issue by thiell** [hpcugent/easybuild-framework#1433]
As a follow-up to https://github.com/hpcugent/easybuild-easyblocks/pull/717 the default value of `src` and `patches` instance variables in `Extension` should be an empty list and not `None`, so that it conforms to `EasyBlock`'s ones and allows iterating over without type-check.

**Comment by boegel** [comment]
@thiell: there's no need to also open an issue if you're going to open a pull request, it's only double work

Just include a clear description in the pull request itself.

I'll close this, follow-up via #1434

**Comment by thiell** [comment]
@boegel: ok got it, sorry, I was following point 3 of "Issue a pull request" in https://github.com/hpcugent/easybuild-framework/blob/master/CONTRIBUTING.md. I agree that's overkill for small patches that are not part of a common issue and won't do it again!
