### ISSUE TITLE
[yeb] add support for automatic conversion of types in (os-)dependencies 

### ISSUE THREAD

**Issue by Caylo** [hpcugent/easybuild-framework#1442]
right now, we have support for autoconverting expected value types for easyconfig parameters 
(i.e the `2.1` in `version: 2.1` would be converted as a float by yaml) - we fixed this in #1428 for simple easyconfig parameters; however it still needs to be done for (os-)dependecies. 

for osdependencies, this means we have to deal with the expected value being a tuple as yaml doesnt support tuples.

**Comment by boegel** [comment]
hmm, maybe the stuff in framework/easyconfig/format/convert.py is useful?

**Comment by boegel** [comment]
dependencies: ~~#1429~~, ~~#1479~~, ~~#1495~~
osdependencies: #1491

following this up through the open PRs
