### ISSUE TITLE
suggestion: add url and description when packaging rpms

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1462]
@rjeschmi I noticed rpms generated with easybuild have empty url and description. This is just cosmetics but you have this info in every easyconfig and FPM supports --description and --url so adding those when generating the rpms should be easy

**Comment by rjeschmi** [comment]
thanks @pescobar this is a good issue and can be fixed.

**Comment by boegel** [comment]
fixed in #1469
