### ISSUE TITLE
Bootstrap should check for a local compiler

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-framework#1501]
For complicated reasons, I've been installing EB on a system that didn't have a compiler installed.

The bootstrap script complained about the lack of libibverbs-devel when I tried to build HPL, but at no point did it or EB complain about the lack of a compiler, until I started the build attempt.

**Comment by boegel** [comment]
The bootstrap checking for a compiler doesn't make a lot of sense to me...

Complaining that there's no system compiler available to build GCC with makes sense, but it's possible you run into other problems first, like a missing OS dependency...

**Comment by verdurin** [comment]
Sorry, this is rather garbled, the result of doing everything in a hurry.

I suppose what I meant was that somewhere there should be a check for a working compiler, as an OS dependency, because clearly you won't get far without it. Even just mentioning it in the installation documentation would help.

In this case I was stuck on a specific node with an unhelpful configuration and needed to try something very quickly.

**Comment by boegel** [comment]
@verdurin: it is documented: http://easybuild.readthedocs.org/en/latest/Installation.html#dependencies

**Comment by verdurin** [comment]
Bah. Please forget this ever happened.
