### ISSUE TITLE
Building binutils at the same time as GCC

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-framework#1518]
It looks like building binutils at the same time as GCC is quite common:
http://stackoverflow.com/questions/1726042/recipe-for-compiling-binutils-gcc-together
This could avoid some of the overhead we currently have in getting to our GCC build. It's at least worth a bit of investigation.

Linuxfromscratch do it in as a bootstrap though and it might be good to understand why:
http://www.linuxfromscratch.org/lfs/view/development/index.html

**Comment by boegel** [comment]
@ocaisa: this belongs in the easyblocks repo?

**Comment by ocaisa** [comment]
Ok, moving
