### ISSUE TITLE
packaging fails when homepage = '(none)'

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1527]
I just found that packaging fails with some easyconfigs which have ```homepage = '(none)'```. As example this one fails
https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/g/goolf/goolf-1.7.20.eb

Here you have a debug log:
https://gist.github.com/02ce3baf6fe8afbc46ce

As temporary workaround I just defined a homepage for this toolchain using url http://easybuild.readthedocs.org/en/latest/eb_list_toolchains.html

Maybe the proper solution is to check the content of the ```homepage``` variable and skip using it in case it's not valid? 

CC: @rjeschmi

**Comment by rjeschmi** [comment]
Yeah I already caught this. It is a problem with escaping properly.

**Comment by rjeschmi** [comment]
hmm I can't find my fix, but it is trivial, so I'll patch again and test.

**Comment by boegel** [comment]
fixed by #1530, let's follow up there
