### ISSUE TITLE
make sure no modules are loaded when EasyBuild is started

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#153]
(old internal ticket 346)

EasyBuild should check whether (software) modules (built with EasyBuild) were loaded when it stars, and refuse to continue if it detects it.

Having modules loaded outside of EasyBuild could make or break build, and the result may be different with an environment in which no modules were loaded.

Currently, it only checks whether the software it is trying to built is loaded, but it should do the same for dependencies and non-dependencies.

**Comment by damianam** [comment]
Update on this ancient issue:

I think it makes sense to have an option to unload everything except a set of modules listed in a whitelist. At least in our setup that will be a nice way to sanitize the environment without breaking other things.

**Comment by wpoely86** [comment]
@damianam use sticky modules?

**Comment by damianam** [comment]
We have a module for setting up EB related variables. And another one for GC3Pie. And another one for EB itself. I don't want to make them sticky and force me to use `--purge` in my shell just to allow EB to have an easier way to sanitize its environment prior to running. That is for our case, but other people might have other reasons to keep other modules loaded, and not make them sticky.  It has implications in the environment outside of EB, doesn't seem like a clean solution to me.

**Comment by ocaisa** [comment]
You could just make sure there are no modules loaded that define `EBROOT*`, that's pretty clean I think

**Comment by damianam** [comment]
It is clean in our case, but if somebody mixes EB modules with other modules that shouldn't be loaded when installing software it wouldn't be enough. Besides that, it would unload the EasyBuild module, so you would have to make at least one exception already

**Comment by ocaisa** [comment]
I think you'd be safe if you only unloaded the modules after the EB process has finished grabbing its configuration

**Comment by migueldiascosta** [comment]
I think I just hit this problem with a `PythonPackage` (e.g. GPAW) that depends on another one (e.g. ASE), in a counterintuitive way: if ASE is already loaded, the sanity check fails saying ASE cannot be found, but if ASE is not loaded, the sanity check passes

Because it is counterintuive, it would be helpful that at least some warning was issued at the beginning saying a dependency shouldn't be loaded

(in any case, why doesn't the sanity check find/reload the dependency when it was already loaded?)

**Comment by vanzod** [comment]
I also hit the same problem when trying to build `Python` with `foss` toolchain when the `ncurses` library built with the `dummy` toolchain has been built with separate terminfo symbols (see PR #3545) as described in #4049.

I would personally prefer to have EB purge the environment if modules are loaded (with the exception of the EB module) and then restore them after the installation is completed. This behavior can be overridden with a flag for those who want to keep the modules loaded.

**Comment by boegel** [comment]
I guess different sites/people would have differences preferences here...

We could implement a detection mechanism for this (that ignores a loaded EasyBuild module), with a couple of different options as to how EasyBuild should respond:

* `--detect-loaded-modules=warn`: print a big fat warning if any (EasyBuild-generated) modules are loaded, mentioning that this may affect the installations done by EasyBuild
* `--detect-loaded-modules=error`: same, but make it a fatal error
* `--detect-loaded-modules=warn,purge`: warn about having modules loaded, but run a `module purge` and continue; it should be OK to also unload the EasyBuild module, since EasyBuild is already running (not 100% sure about this one though...)

The detection mechanism should probably look at `$EBROOT*` environment variables, since just checking module names in the output of `module list` is not going to work imho.

I guess we'll also need some kind of ignore list (`--ignore-loaded-modules=...`), since some stuff may be provided to EasyBuild via a module installed with EasyBuild, e.g. GC3Pie (for `--job`), PyYAML (for `.yeb` easyconfigs), etc...

**Comment by boegel** [comment]
fixed in #2228, let's follow up there in context of the proposed enhancements...
