### ISSUE TITLE
View EasyBuild log files without cut-n-paste

### ISSUE THREAD

**Issue by citibeth** [hpcugent/easybuild-framework#1540]
I frequently get EasyBuild errors.  Then I have to cut-n-paste out of my command window, in order to see the errors.  In fact, I have to cut-n-paste the RIGHT filename out of a bunch of text.  For example:

```
gs611-tyndall:app rpfische$ eb UDUNITS-2.2.19-GCC-4.9.3.eb
PYTHONPATH= /Users/rpfische/ebx/pylib
== temporary log file in case of crash /var/folders/n2/0ll2lwm50b91f5ppmyggd_g4cdc3y3/T/eb-yNa2wa/easybuild-Ab31tE.log
== resolving dependencies ...
== processing EasyBuild easyconfig /Users/rpfische/git/usermacports/ebx/easyconfigs/app/UDUNITS-2.2.19-GCC-4.9.3.eb
== building and installing UDUNITS/2.2.19-GCC-4.9.3...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /Users/rpfische/eb/easybuild/build/UDUNITS/2.2.19/GCC-4.9.3): build failed (first 300 chars): Couldn't find file udunits-2.2.19.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /Users/rpfische/git/usermacports/ebx/easyconfigs/app/u/UDUNITS/udunits-2.2.19.tar.gz, /Users/rpfische/git/usermacports/ebx/easyconfigs/app/UDUNITS/udunits-2.2.19.tar.gz, /Users/rpf
== Results of the build can be found in the log file /var/folders/n2/0ll2lwm50b91f5ppmyggd_g4cdc3y3/T/eb-yNa2wa/easybuild-UDUNITS-2.2.19-20160108.114133.xMUeN.log
ERROR: Build of /Users/rpfische/git/usermacports/ebx/easyconfigs/app/UDUNITS-2.2.19-GCC-4.9.3.eb failed (err: "build failed (first 300 chars): Couldn't find file udunits-2.2.19.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /Users/rpfische/git/usermacports/ebx/easyconfigs/app/u/UDUNITS/udunits-2.2.19.tar.gz, /Users/rpfische/git/usermacports/ebx/easyconfigs/app/UDUNITS/udunits-2.2.19.tar.gz, /Users/rpf")
```

It would be nice if things were easier here.  For example... what if EasyBuild made a symlink to the latest .log file produced, and put that symlink in a standard place.  Then I could just "less" on the symlink, which is always named the same thing.

**Comment by boegel** [comment]
@citibeth: I like this idea... I guess the question is then where to put the symlink, since multiple concurrent builds may be running at the same time, and you may be on a shared filesystem...

Maybe there's a better alternative?

Defining an environment variable somehow is another option, but since `eb` is running a subshell that won't work either.

**Comment by citibeth** [comment]
Maybe just put it in $HOME/.eblog or something.  If multiple concurrent
builds are going at once by the same user... well, you can always
cut-n-paste from the log like we do now.

**Comment by boegel** [comment]
How about something like this: you take control over where EasyBuild puts the temporary log file (which includes the logs for all builds being performed during that `eb` session, cfr. http://easybuild.readthedocs.org/en/latest/Logfiles.html) using the `--tmp-logdir` configuration setting (e.g. via `$EASYBUILD_TMP_LOGDIR`), which at least enables you easier access to the log file.

And, with a command like:

```
vim `ls -rt $EASYBUILD_TMP_LOGDIR/easybuild*log | tail -1`
```

You can access the last log file fairly pretty easily. You can define a helper function in your .bashrc maybe, something like `eblog`...

If you define `$EASYBUILD_TMP_LOGIDR` to something like ```/tmp/$USER/$$```, you're basically sure the logs files of different parallel sessions won't be overwriting each other...

**Comment by citibeth** [comment]
Sounds good to me.  Just one more thing... why not put the helper function
into easybuild?  This should be as easy as possible to set up.  Then you
could do something like:

> eb xyz.eb
... error happens...
> less `eb xyz.eb --logfile`

**Comment by boegel** [comment]
@citibeth: that may be harder than it seems. What if I do `eb abc.eb --logfile` instead? Checking which log file to pick up is probably not trivial... Also, that kind of requires assumes that `--tmp-logdir` is set to a value such that the location where log files are kept is identical between `eb` sessions (which it's not, by default).

Anyway, food for thought, sure, it's probably not impossible.

**Comment by citibeth** [comment]
I think this conversation has gotten beyond my design know-how of
EasyBuild.  Something that basically does the job, and is easy to
implement, would probably be bets.

**Comment by boegel** [comment]
After you pointed this out @citibeth, it started to annoy me so much that I just implemented the support for this, cfr. #1541.

Let's follow up there and close this issue.

Thanks for bringing this up! Frustrations from 'newcomers' always lead to very useful features that people already used to the tool don't think of.
