### ISSUE TITLE
broken output for Lmod spider

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1582]
I sent a PR some time ago to include the modules descriptions in the output of "module spider" but this has been removed in latest easybuild release. Here there is a more detailed description
https://github.com/hpcugent/easybuild-framework/issues/766

And this is the PR I sent some time ago
https://github.com/hpcugent/easybuild-framework/pull/795

it would be nice to get this back for future releases.

CC: @boegel @geimer

**Comment by pescobar** [comment]
I just sent this PR https://github.com/hpcugent/easybuild-framework/pull/1583 which should fix the issue. 

@boegel @geimer Can you please review? If you agree this fix is fine I will patch my local easybuild installation. I rely in proper spider output to generate the list of available software in our website.

**Comment by geimer** [comment]
@pescobar Since https://github.com/hpcugent/easybuild-framework/pull/1583 is now merged, this issue can probably be closed, right?

**Comment by pescobar** [comment]
yes. closing it.
