### ISSUE TITLE
rpmrebuild as OS dependency in the rpm easyblock, and check_os_dependency

### ISSUE THREAD

**Issue by damianam** [hpcugent/easybuild-framework#1587]
`rpmrebuild` is currently an OS dependency in the RPM easyblock. I think this is not the best way to  handle it, since it might not be available as a system package, but be on `$PATH` anyway. For instance, installed by EB (see https://github.com/hpcugent/easybuild-easyconfigs/pull/2402). This is the case in our setup.

I think it can be an explicit dependency using the PR listed above, and/or simply check if it is in the path. That takes me to `check_os_dependency`. It will return `False` if the dependency is available in the OS repos, but not installed. Regardless of its presence in `$PATH`. Is that the intended behaviour? It looks to me like this:

```
def check_os_dependency(dep):
...
    if cmd is None:
        # fallback for when os-dependency is a binary/library
        found = which(dep)
...
```

wants to check for simply binaries, but `cmd` will not be `None` if `rpm` or `dpkg` exist.

Is that a bug or am I missing something?

**Comment by ocaisa** [comment]
In the rpm easyblock just check for the os dep or EBROOTRPMREBUILD.

**Comment by damianam** [comment]
@ocaisa that's a reasonable fix for the easyblock, but the question about `check_os_dependency` is still open

**Comment by damianam** [comment]
@boegel any comment on this?

**Comment by boegel** [comment]
Just checking whether `rpmrebuild` is available (using the `which` function) should do it, we shouldn't really care where it comes from.

@damianam: what `check_os_dependency` is doing is falling back to simply checking whether `foo` is a binary that is available through `$PATH`, if neither the `rpm` or `dpkg` commands are available, as a poor mans way of checking for an OS dependency.

If `rpm` or `dpkg` *is* available, it relies on whatever querying it results in.

Does that answer your question?

**Comment by damianam** [comment]
Yes. I was a bit confused, because of the fallback. It looked like it wanted to do something different.

Bottom line: `check_os_dependency `should be replaced by `which` in `rpm.py`. I guess opening a PR is not really necessary in this case. Or is it?

**Comment by boegel** [comment]
Well, if you want it to happen... :)

**Comment by damianam** [comment]
There you go: https://github.com/hpcugent/easybuild-easyblocks/pull/864

**Comment by boegel** [comment]
Thanks @damianam, let's follow-up there
