### ISSUE TITLE
improvement suggestion: add "pyshortver" as a template

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1594]
when installing python packages these lines are copied&pasted in many different easyconfigs

```
python = 'Python'
pythonversion = '2.7.9'
pyshortver = '.'.join(pythonversion.split('.')[:2])
```

See this search: https://github.com/hpcugent/easybuild-easyconfigs/search?utf8=%E2%9C%93&q=pyshortver

I think it would be nice if the framework provides a template ```%(pyshortver)s``` when it detects a python module as dependency. I think we would avoid a lot of copy&paste code in the easyconfigs.

**Comment by boegel** [comment]
Good suggestion, but not entirely trivial...

The easyconfig needs to be parsed first to see whether `Python` is listed as a (direct) dep, so you have a chicken-egg situation there...

**Comment by pescobar** [comment]
to make things better sometimes we use ```pyshortver``` and sometimes ```pythonshortver```. See:

https://github.com/hpcugent/easybuild-easyconfigs/search?utf8=%E2%9C%93&q=pythonshortversion&type=Code

it would be nice to get his homogeneous. Wouldn't be a possibility to get the value from the easyconfig names without parsing them?

**Comment by boegel** [comment]
OK, seems easier than I thought it would be, see #1595, let's follow-up there
