### ISSUE TITLE
--minimal-toolchains seems to don't work with ToolchainMNS

### ISSUE THREAD

**Issue by damianam** [hpcugent/easybuild-framework#1606]
Apparently ToolchainMNS needs an easyconfig file for each dependency, so --minimal-toolchains doesn't work, it crashes even before trying to use minimal toolchains. The attached log shows an debug example. @ocaisa can probably share more details.

[crash.zip](https://github.com/hpcugent/easybuild-framework/files/126694/crash.zip)

**Comment by boegel** [comment]
Is this 'just' a matter of doing the mininal-toolchains-aware-robot-search earlier, i.e. when the module naming scheme needs to figure out the module name for the dependencies (and why does it even need to do that)?

**Comment by ocaisa** [comment]
Should be solved with #1614

**Comment by boegel** [comment]
a test that checks for this is added in #1619; it should pass when #1614 is merged in

**Comment by boegel** [comment]
@damianam: ok to close?

**Comment by damianam** [comment]
@boegel ok to close

**Comment by boegel** [comment]
@damianam: then close it ;)

I prefer not to close issues opened by others (except when merging stuff, of course).
