### ISSUE TITLE
Build-dependencies cannot use the `Name: version` syntax [yeb]

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-framework#1692]
This abridged syntax is accepted by `dependencies:` in `.yeb` files::

        dependencies:
          - Autoconf: 2.69

However, the same syntax is *not* accepted in the `builddependencies`
(and possibly other) sections; EB errors out:

        ERROR: Failed to process easyconfig /net/nfs4/nfs.hydra/home/rmurri/givaro.yeb: Dependency specified without name: {'external_module_metadata': {}, 'full_mod_name': None, 'build_only': True, 'versionsuffix': '', 'external_module': False, 'dummy': False, 'Autoconf': 2.69, 'toolchain': {'version': '2015a', 'name': 'foss'}, 'name': None, 'short_mod_name': None, 'version': None, 'hidden': False}

**Comment by boegel** [comment]
fixed in #1818, thanks for reporting this @riccardomurri!
