### ISSUE TITLE
Relax download timeout (or at least provide a config option for it)

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-framework#1693]
I am using EB on my laptop with the network connection going over
wireless LAN which -for some reason- takes a lot of time to perform
the TCP handshake and start downloads.  EB constantly fails the
"fetch" phase::

        == resolving dependencies ...
        == processing EasyBuild easyconfig /home/rmurri/w/easybuild/easyconfigs/easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016a.eb
        == building and installing FFTW/3.3.4-gompi-2016a...
        == fetching files...
        == FAILED: Installation ended unsuccessfully (build directory: /tmp/FFTW/3.3.4/gompi-2016a): build failed (first 300 chars): Couldn't find file fftw-3.3.4.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /home/rmurri/w/easybuild/easyconfigs/easybuild/easyconfigs/f/FFTW/f/FFTW/fftw-3.3.4.tar.gz, /home/rmurri/w/easybuild/easyconfigs/easybuild/easyconfigs/f/FFTW/FFTW/fftw-3.3.4.tar.gz, /h

However, if I download the same file via `wget`, all is fine
eventually (it just takes some ~30 seconds to start the download).

It would be nice if EB's timeout parameters were more lax or at least
adjustable.

**Comment by boegel** [comment]
@riccardomurri We already have an option to adjust the default download timeout:

```
    --download-timeout=DOWNLOAD-TIMEOUT
                        Timeout for initiating downloads (in seconds) (type
                        <type 'float'>)
```

**Comment by riccardomurri** [comment]
Sorry for the noise - I should've looked better.
