### ISSUE TITLE
Overview of changes shown by `eb --new-pr` is not correct

### ISSUE THREAD

**Issue by SimonPinches** [hpcugent/easybuild-framework#1694]
For example `eb ant-1.9.6-Java-1.7.0_79.eb  --new-pr --experimental` shows

Opening pull request
* target: hpcugent/easybuild-easyconfigs:develop
* from: SimonPinches/easybuild-easyconfigs:20160325094024_new_pr_ant196
* title: "{devel}[dummy/] ant v1.9.6"
* description:
"""
(created using `eb --new-pr`)

"""
* overview of changes:
 .../easyconfigs/z/zsync/zsync-0.6.2-ictce-5.3.0.eb | 32 ++++++++++++++++++++++
 1 file changed, 32 insertions(+)

The PR has nothing to do with zsync...

**Comment by Caylo** [comment]
@SimonPinches I can't seem to recreate this, does this still happen to you?

**Comment by boegel** [comment]
Must have been a glitch in the matrix... I'll close this, please let us know if you see this popping up again @SimonPinches!
