### ISSUE TITLE
CPU target specific libsci not being picked up 

### ISSUE THREAD

**Issue by pforai** [hpcugent/easybuild-framework#1703]
We use `$CRAY_LIBSCI_PREFIX_DIR` which points to the generic X86_64 installation, not a CPU model specific one.

For example for libsci 13.0.4 there are the following optimized builds 
```sh
/opt/cray/libsci/13.0.4/CRAY/83/ivybridge
/opt/cray/libsci/13.0.4/CRAY/83/istanbul
/opt/cray/libsci/13.0.4/CRAY/83/haswell
/opt/cray/libsci/13.0.4/CRAY/83/interlagos
/opt/cray/libsci/13.0.4/CRAY/83/sandybridge
/opt/cray/libsci/13.0.4/CRAY/83/mc12
/opt/cray/libsci/13.0.4/CRAY/83/mc8
/opt/cray/libsci/13.0.4/CRAY/83/abudhabi
```
While we end up using `/opt/cray/libsci/13.0.4/CRAY/83/x86_64/` since `$CRAY_LIBSCI_PREFIX_DIR` only points to this.

cc @gppezzi

**Comment by boegel** [comment]
so, we should take `optarch` into account when determine the value to use for `$EBROOTLIBSCI` and such?

**Comment by boegel** [comment]
Basically, we use `$CRAY_LIBSCI_PREFIX_DIR/../$EASYBUILD_OPTARCH` rather than `$CRAY_LIBSCI_PREFIX_DIR`

**Comment by boegel** [comment]
@pforai I seem to remember someone confirmed to us that there is no architecture-specific `libsci`, so this can be closed?

**Comment by boegel** [comment]
@pforai ping on closing this?

**Comment by gppezzi** [comment]
All those entries look like symlinks to the `x86_64` folder...

**Comment by pforai** [comment]
I think G is right, this is not relevant any more and we're not doing it wrong as far as I can tell.
