### ISSUE TITLE
eb command fails

### ISSUE THREAD

**Issue by gbalduzz** [hpcugent/easybuild-framework#1707]
I am having a problem installing easybuild on Ubuntu 15.
I ran the bootstrap file, load the module EasyBuild (with modulecmd) with the following output
`EBDEVELEASYBUILD=/home/giovanni/.local/software/EasyBuild/2.7.0/easybuild/EasyBuild-2.7.0-easybuild-devel ;export EBDEVELEASYBUILD;EBROOTEASYBUILD=/home/giovanni/.local/software/EasyBuild/2.7.0 ;export EBROOTEASYBUILD;EBVERSIONEASYBUILD=2.7.0 ;export EBVERSIONEASYBUILD;LOADEDMODULES=EasyBuild/2.7.0 ;export LOADEDMODULES;PATH=/home/giovanni/.local/software/EasyBuild/2.7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/giovanni/.mypath/:/usr/local/cuda-7.5/bin:/home/giovanni/Clion/bin ;export PATH;PYTHONPATH=/home/giovanni/.local/software/EasyBuild/2.7.0/lib/python2.7/site-packages ;export PYTHONPATH;_LMFILES_=/home/giovanni/.local/modules/all/EasyBuild/2.7.0 ;export _LMFILES_;`

But when I try to run eb it says: /usr/bin/python2: No module named easybuild. Am I missing a step?
Best regards, Giovanni

**Comment by boegel** [comment]
@gbalduzz To load the EasyBuild module, you should use `module load EasyBuild`, not `modulecmd bash load EasyBuild`.

The latter command only prints the changes to the environment, rather than applying them. The `module` function is a wrapper for `modulecmd` that also applies the changes to the current environment.

Let us know if this helps.

**Comment by gbalduzz** [comment]
Thank you very much! I never had to install a module manager.

**Comment by boegel** [comment]
@gbalduzz In that case, I highly recommend looking into Lmod instead. The environment modules project is not actively maintained, while Lmod is, *and* it has a bunch of features that the abandoned project doesn't have.
See http://lmod.readthedocs.org/.
