### ISSUE TITLE
Unable to install Easybuild by any of the suggested methods

### ISSUE THREAD

**Issue by RalphTheBest** [hpcugent/easybuild-framework#1714]
**Hello,**

**I've been trying these last days to install Easybuild in my pc. Unfortunately, the bootstrap script is failing me. I've tried also all the alternative methods, and they are failing for me too, so I really don't know which may be the problem.**

**Here is the complete trace I get when I execute the bootstrap script:**

[[INFO]] Installation prefix /home/adrian/Apps/EasyBuild
[[INFO]] Fetching sources from /home/adrian/Downloads...
[[INFO]] 

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...

Downloading http://hpcugent.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
Extracting in /tmp/tmpkZrOEY
Now working in /tmp/tmpkZrOEY/distribute-0.6.49
Installing Distribute
[[INFO]] 

+++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] Fetching sources from /home/adrian/Downloads...
[[INFO]] Found /home/adrian/Downloads/easybuild-framework-2.7.0.tar.gz for easybuild-framework package
[[INFO]] Found /home/adrian/Downloads/easybuild-easyblocks-2.7.0.tar.gz for easybuild-easyblocks package
[[INFO]] Found /home/adrian/Downloads/easybuild-easyconfigs-2.7.0.tar.gz for easybuild-easyconfigs package
[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpPriAbP/eb_stage1 /home/adrian/Downloads/easybuild-framework-2.7.0.tar.gz /home/adrian/Downloads/easybuild-easyblocks-2.7.0.tar.gz /home/adrian/Downloads/easybuild-easyconfigs-2.7.0.tar.gz'
Installing with setuptools.setup...
Installing version 2.7.0 (API version 2)
INFO: This is (based on) vsc.install.shared_setup 0.9.19
INFO: run_tests from base dir /tmp/easy_install-CgcaCy/vsc-base-2.4.18 (using executable /tmp/easy_install-CgcaCy/vsc-base-2.4.18/setup.py)
WARN: cleanup lib/vsc_base.egg-info
INFO: generated list: ['vsc', 'vsc.utils']
INFO: generated packages list: ['vsc', 'vsc.utils']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /tmp/easy_install-CgcaCy/vsc-base-2.4.18/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
INFO: found match url https://github.com/hpcugent/vsc-base in /tmp/easy_install-CgcaCy/vsc-base-2.4.18/PKG-INFO
INFO: found match name vsc-base in /tmp/easy_install-CgcaCy/vsc-base-2.4.18/PKG-INFO
INFO: Removing None download_url
INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-base', 'name': 'vsc-base'}
INFO: using long_description Common tools used within our organization. Originally created by the HPC team of Ghent University (http://ugent.be/hpc).
INFO: generated list: ['bin/optcomplete.bash', 'bin/startlogdaemon.sh', 'bin/logdaemon.py']
INFO: generated scripts list: ['bin/optcomplete.bash', 'bin/startlogdaemon.sh', 'bin/logdaemon.py']
INFO: Checking .pth file support in .
INFO: /usr/bin/python -E -c pass
INFO: Searching for vsc-install>=0.9.19
INFO: Reading http://pypi.python.org/simple/vsc-install/
INFO: Best match: vsc-install 0.9.19
INFO: Downloading https://pypi.python.org/packages/source/v/vsc-install/vsc-install-0.9.19.tar.gz#md5=db8c042144fe59acce6d5ba61693ff4f
INFO: Processing vsc-install-0.9.19.tar.gz
INFO: Writing /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19/setup.cfg
INFO: Running vsc-install-0.9.19/setup.py -q bdist_egg --dist-dir /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19/egg-dist-tmp-lTFiDr
INFO: This is (based on) vsc.install.shared_setup 0.9.19
INFO: run_tests from base dir /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19 (using executable /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19/setup.py)
INFO: not enforcing prospector support. run "easy_install propspector" yourself
WARN: cleanup lib/vsc_install.egg-info
INFO: generated list: ['vsc.install', 'vsc']
INFO: generated packages list: ['vsc.install', 'vsc']
INFO: makesetupcfg set to True, (re)creating setup.cfg
INFO: found license /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
INFO: setting license LGPLv2+
INFO: No name defined, trying to determine it
INFO: found match url https://github.com/hpcugent/vsc-install in /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19/PKG-INFO
INFO: found match name vsc-install in /tmp/easy_install-CgcaCy/vsc-base-2.4.18/temp/easy_install-lupANF/vsc-install-0.9.19/PKG-INFO
INFO: Removing None download_url
INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-install', 'name': 'vsc-install'}
INFO: using long_description vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group
INFO: generated list: []
INFO: generated scripts list: []
WARN: zip_safe flag not set; analyzing archive contents...
WARN: vsc.fancylogger: module references __file__
WARN: vsc.install.shared_setup: module references __file__
WARN: vsc.install.shared_setup: module references __path__
WARN: vsc.install.shared_setup: module MAY be using inspect.getsource
INFO: 
Installed /tmp/easy_install-CgcaCy/vsc-base-2.4.18/vsc_install-0.9.19-py2.7.egg
WARN: zip_safe flag not set; analyzing archive contents...
WARN: vsc.utils.fancylogger: module MAY be using inspect.stack
WARN: vsc.utils.exceptions: module MAY be using inspect.getouterframes
WARN: vsc.utils.generaloption: module MAY be using inspect.stack
WARN: cleanup lib/vsc_install.egg-info
WARN: zip_safe flag not set; analyzing archive contents...
WARN: vsc.fancylogger: module references __file__
WARN: vsc.install.shared_setup: module references __file__
WARN: vsc.install.shared_setup: module references __path__
WARN: vsc.install.shared_setup: module MAY be using inspect.getsource
INFO: Installing with setuptools.setup...
INFO: Installing version 2.7.0 (required versions: API >= 2)
INFO: Installing with setuptools.setup...
INFO: Installing version 2.7.0 (required versions: API >= 2, easyblocks >= 2.7)
WARN: warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

[[INFO]] 

+++ STAGE 2: installing EasyBuild in /home/adrian/Apps/EasyBuild with EasyBuild from stage 1...

== temporary log file in case of crash /tmp/eb-QmTgpl/easybuild-PrmDxx.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 760, in <module>
    main()
  File "bootstrap_eb.py", line 563, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 481, in stage2
    easybuild_main()
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/main.py", line 280, in main
    modlist = session_module_list(testing=testing)  # build options must be initialized first before 'module list' works
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/testing.py", line 143, in session_module_list
    modtool = modules_tool(testing=testing)
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 1002, in modules_tool
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 807, in __init__
    super(Lmod, self).__init__(*args, **kwargs)
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 180, in __init__
    self.check_module_path()
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 328, in check_module_path
    self.prepend_module_path(eb_modpath)
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 869, in prepend_module_path
    self.use(path)
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 289, in use
    self.run_module(['use', path])
  File "/tmp/tmpPriAbP/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.7.0-py2.7.egg/easybuild/tools/modules.py", line 523, in run_module
    proc = subprocess.Popen(cmdlist + args, stdout=PIPE, stderr=PIPE, env=environ)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Here are the output of the commands indicated in the documentation:**

$python -V
Python 2.7.6

$type module
module is a function
module () 
{ 
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}

$type -f module
bash: type: module: not found

$module --version

Modules based on Lua: Version 6.1  2016-02-05 16:31
    by Robert McLay mclay@tacc.utexas.edu

$ module av EasyBuild

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

$which -a eb
(No answer)

$eb --version
eb: command not found

**I know this problem may be trivial in the end, but I tried all the suggested methods and solutions for common problems and none worked, so I would really apreciate if someone could tell me if there is something wrong with the installation procedure or it's actually my mistake here.**

**Thanks.**

**Comment by RalphTheBest** [comment]
Sorry for bothering you. I just achieved the successful instalation by using a local version of Lmod instead of a global one.

**Comment by boegel** [comment]
@RalphTheBest for what it's worth: I think the `lmod` that EasyBuild was picking up via `$PATH` was probably not the binary command employed by the `module` function, which would explain the `OSError` you ran into

Good to hear that you were able to resolve the problem yourself!

**Comment by RalphTheBest** [comment]
I'll give a look to that, just in case.
Thanks for the help. I really appreciate it.
