### ISSUE TITLE
--new-pr should be able to handle patch files

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-framework#1738]
When I was trying to use `--new-pr` to update SAMtools, I needed to include an updated Makefile patch.

`--new-pr` thought that the patch file I included was an `easyconfig`, so it complained about the lack of an `easyblock` specification.

I suppose this implies the need for a new option to indicate which files are patches.

**Comment by boegel** [comment]
@verdurin I included a pointer to this in #1674

We can probably detect whether something is a patch file, but the hard bit is to figure out where the patch files should be located...
Maybe we need to look through the `patches` values in the easyconfig files being included, and figure out where the patch belongs.

**Comment by boegel** [comment]
work-in-progress PR for this:# 1751

**Comment by boegel** [comment]
fixed in #1751
