### ISSUE TITLE
Cache-able calls to "module show ..." and "module avail"

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-framework#1739]
In our use case (`--minimal-toolchains` coupled with `--use-existing-modules`) we now have (after #1735) exactly one `use` call for a dry run for `Python/2.7.11`:
```
$ grep "Running module" easybuild-uDHESA.log | grep "python use " | wc -l 
       1
```
There is quite a bit of `show`, maybe there's an opportunity for caching there too (about 0.3s each, at first look):
```
$ grep "Running module" easybuild-uDHESA.log | grep "python show " | wc -l
     155
```
and even more so for `avail`
```
$ grep "Running module" easybuild-uDHESA.log | grep -v "python .* avail "  | wc -l
     158
```
158 calls to "avail", all of them without arguments and each takes about 1-1.5s to run, at first glance.

so, lot's of more opportunity for speedups after fixing the `module use` issue #1735 :-)

**Comment by boegel** [comment]
fixed in #1742
