### ISSUE TITLE
detection of libpng of R fails when `libpng` is a hidden dependency

### ISSUE THREAD

**Issue by gppezzi** [hpcugent/easybuild-framework#1744]
Seems related to https://github.com/hpcugent/easybuild-framework/issues/1340

if I load libpng/1.6.21-gmvolf-15.11 I see the following output from configure:
```
checking for png_create_write_struct in -lpng... yes
````

if I load libpng/.1.6.21-gmvolf-15.11 (pointing to the same libpng build):
```
checking for png_create_write_struct in -lpng... no
```

Any thoughts?

**Comment by gppezzi** [comment]
After some additional tests, it also fails if libpng is not hidden (so this is not related to #1340). 

It could be a conflict with the system libpng...

**Comment by boegel** [comment]
@gppezzi can you try again using `--stop configure`, and then upload the EB debug log and the `config.log` somewhere?

**Comment by gppezzi** [comment]
After checking the config.log, I see that the actual problem is that configure is using the system zlib when checking for libpng:
```
/xxx/libpng/1.6.16-gmvolf-15.11/lib/libpng.so: undefined reference to `inflateReset2@ZLIB_1.2.3.4'
```
So for the moment being i'm using the system libs for png & z (don't have much time to debug this now)

@boegel do you think that this could be affecting other R builds or this is something specific to our setup here?

**Comment by boegel** [comment]
@gppezzi not sure, I'd need to see a full debug log and get more details about your configuration...

Are you using `--filter-deps`?

**Comment by gppezzi** [comment]
I'm closing this since we're using the system zlib/libpng and users are happy, i'll re-open if needed.
