### ISSUE TITLE
Have a unit test against borken `module use`

### ISSUE THREAD

**Issue by fgeorgatos** [hpcugent/easybuild-framework#1756]

**Comment by boegel** [comment]
```
module use /tmp/modules
echo $MODULEPATH
bash
echo $MODULEPATH
```

**Comment by fgeorgatos** [comment]
example of the bug against recent fedora, patched last month:
https://bugzilla.redhat.com/show_bug.cgi?id=1326075

**Comment by fgeorgatos** [comment]
Example of the bug:
```
[root@bright-lmod ~]# wget ftp://195.220.108.108/linux/epel/6/x86_64/Lmod-6.0.15-2.el6.noarch.rpm
[...]
[root@bright-lmod ~]# md5sum Lmod-6.0.15-2.el6.noarch.rpm
36d074c7875a02d32f227abb4a553a78  Lmod-6.0.15-2.el6.noarch.rpm
[root@bright-lmod ~]# yum localinstall !$
yum localinstall Lmod-6.0.15-2.el6.noarch.rpm
[...]
Installed:
  Lmod.noarch 0:6.0.15-2.el6

Complete!
[root@bright-lmod ~]# su - fgeorgatos
Last login: Fri May  6 14:32:36 CEST 2016 from 46.17.164.10 on pts/3
[fgeorgatos@bright-lmod ~]$ echo $MODULEPATH
/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core
[fgeorgatos@bright-lmod ~]$ module use $HOME/.local/easybuild/modules.all
[fgeorgatos@bright-lmod ~]$ echo $MODULEPATH
/home/fgeorgatos/.local/easybuild/modules.all:/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core
[fgeorgatos@bright-lmod ~]$ bash
[fgeorgatos@bright-lmod ~]$ echo $MODULEPATH
/etc/modulefiles:/usr/share/modulefiles:/usr/share/Modules/modulefiles
[fgeorgatos@bright-lmod ~]$
```

btw. the bug is expected to have vanished for most new installs, since the fresher 6.3.1 rollouts:
https://www.rpmfind.net/linux/rpm2html/search.php?query=Lmod

Interestingly, the other bug `ml --gitversion` does not appear to be fixed. 
That has been fixed in this Lmod .spec though: https://github.com/plabrop/bic/issues/13

**Comment by boegel** [comment]
fixed in #1758, let's follow up there?

**Comment by fgeorgatos** [comment]
yeap, nice job there.

btw. I forgot to mention that, also ohpc probably has this issue, as well as any hpc site, 
with unguarded blind setting of MODULEPATH to a fixed value. candidate example (as of today):
https://github.com/openhpc/ohpc/blob/master/components/admin/lmod/SPECS/lmod.spec#L111

**Comment by boegel** [comment]
@fgeorgatos Thanks for the feedback, PR going in. Have you reported that to OpenHPC? If not, you should.

**Comment by fgeorgatos** [comment]
i'm pretty sure I had reported it back then, although I can no longer trace the proof..
