### ISSUE TITLE
x265 install

### ISSUE THREAD

**Issue by eediaz1987** [hpcugent/easybuild-framework#1773]
i'm tryibg to install ffmpeg, and i have all dependencies instaled except x265, but when i  have this error:

2016-05-18 15:20:40,963 runpy ERROR build failed (first 300 chars): cmd " cmake . -DCMAKE_INSTALL_PREFIX=/opt/librarieshpc/easybuild/software/x265/1.9-goolf-1.7.20 -DCMAKE_C_COMPILER='gcc' -DCMAKE_Fortran_FLAGS='-O2 -march=native' -DCMAKE_CXX_FLAGS='-O2 -march=native' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_C_FLAGS='-O2 -march=native'  (at easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/easybuild/main.py:116 in build_and_install_software)
== 2016-05-18 15:20:40,968 runpy ERROR Build of /opt/librarieshpc/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.6.0-py2.7.egg/easybuild/easyconfigs/x/x265/x265-1.9-goolf-1.7.20.eb failed (err: 'build failed (first 300 chars): cmd " cmake . -DCMAKE_INSTALL_PREFIX=/opt/librarieshpc/easybuild/software/x265/1.9-goolf-1.7.20 -DCMAKE_C_COMPILER=\'gcc\' -DCMAKE_Fortran_FLAGS=\'-O2 -march=native\' -DCMAKE_CXX_FLAGS=\'-O2 -march=native\' -DCMAKE_CXX_COMPILER=\'g++\' -DCMAKE_Fortran_COMPILER=\'gfortran\' -DCMAKE_C_FLAGS=\'-O2 -march=native\' ') (at easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/easybuild/main.py:148 in build_and_install_software)
ERROR: Build of /opt/librarieshpc/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.6.0-py2.7.egg/easybuild/easyconfigs/x/x265/x265-1.9-goolf-1.7.20.eb failed (err: 'build failed (first 300 chars): cmd " cmake . -DCMAKE_INSTALL_PREFIX=/opt/librarieshpc/easybuild/software/x265/1.9-goolf-1.7.20 -DCMAKE_C_COMPILER=\'gcc\' -DCMAKE_Fortran_FLAGS=\'-O2 -march=native\' -DCMAKE_CXX_FLAGS=\'-O2 -march=native\' -DCMAKE_CXX_COMPILER=\'g++\' -DCMAKE_Fortran_COMPILER=\'gfortran\' -DCMAKE_C_FLAGS=\'-O2 -march=native\' ')

here i atach the log

**Comment by eediaz1987** [comment]
[easybuild log.txt](https://github.com/hpcugent/easybuild-framework/files/274654/easybuild.log.txt)

**Comment by boegel** [comment]
@eediaz1987:

```
CMake Error: The source directory "/opt/librarieshpc/easybuild/build/x265/1.9/goolf-1.7.20/x265_1.9" does not appear to contain CMakeLists.txt.
```

Which easyconfig file did you use here?

**Comment by eediaz1987** [comment]
x265-1.9-goolf-1.7.20.eb

**Comment by boegel** [comment]
@eediaz1987 yes please, since we don't have this easyconfig in the EB repositories...

**Comment by eediaz1987** [comment]
easyblock = 'CMakeMake'

name = 'x265'
version = '1.9'

homepage = 'http://www.videolan.org/developers/x265.html'
description = """x265 is a free software library and application for encoding video streams into the H.265
 AVC compression format, and is released under the terms of the GNU GPL."""

toolchain = {'name': 'goolf', 'version': '1.7.20'}


source_urls = ['http://ftp.videolan.org/pub/videolan/x265/']
sources = ['x265_%(version)s.tar.gz']

dependencies = [('CMake', '2.8.11'),
                ('Yasm','1.3.0'),]

sanity_check_paths = {
    'files': ['bin/x265', 'include/x265_config.h', 'include/x265.h', 'lib/libx265.a', 'lib/libx265.%s' % SHLIB_EXT],
    'dirs': [],
}

moduleclass = 'vis'

**Comment by boegel** [comment]
@eediaz1987 the `CMakeLists.txt` file is actually in the `source` subdirectory; so, try adding this in the easyconfig file:

```python
start_dir = 'source'
```

**Comment by eediaz1987** [comment]
in witch part of the easyconfig, or it does'nt matter the line

**Comment by boegel** [comment]
@eediaz1987 order doesn't really matter in easyconfig files, but style-wise I would put in between `dependencies` and `sanity_check_paths`

**Comment by eediaz1987** [comment]
ok thanks, i do it an run again and the instalation was successfully

**Comment by eediaz1987** [comment]
thanks its works

2016-05-20 10:54 GMT-04:00 Kenneth Hoste <notifications@github.com>:

**Comment by boegel** [comment]
Excellent, thanks for the follow-up @eediaz1987!

Please consider contributing back your easyconfig file, cfr. https://github.com/hpcugent/easybuild/wiki/Contributing-back (a bit outdated, but still mostly relevant)

**Comment by eediaz1987** [comment]
y sent 2 easyconfig, one for x265 with goolf an other for x264 with goolf
too

2016-05-20 12:37 GMT-04:00 Kenneth Hoste <notifications@github.com>:
