### ISSUE TITLE
Same module name for diferent arch builds

### ISSUE THREAD

**Issue by RalphTheBest** [hpcugent/easybuild-framework#1782]
Hi, 

I've been working this past days in adding support for the Intel Xeon Phi coprocessor . While I think I'm pretty done regarding the compiler part, I've found a new problem. 
Since the option for targeting the Phi is just a toolchainopt in the easyconfig, if I try to install the same software twice (one for the host architecture and one for the Xeon Phi) I'm unable due to both modules being called the same. And even if I could, there would be no way to differentiate them, making a mess for anyone who wants to load them.

I know that the obvious answer is to modify the module naming scheme so it will differentiate between both when naming the modules. However, I haven't found anything that lets me know when I'm using the 'phi' option for the toolchain. Any ideas how to do it? Other ways to make the modules names distinct?

**Comment by boegel** [comment]
@RalphTheBest This type of thing is commonly done by adjusting the `versionsuffix`, which is empty by default, i.e. (in an easyconfig file):

```python
versionsuffix = '-phi'
```

The `versionsuffix` is part of the module name by default, and is easily accessible in the module naming scheme. However, that would be a manual process, you would need to make sure you specify/modify the `versionsuffix` together with enabling `phi` in the `toolchainopts`.

To access toolchain options, you could access the (equivalent of) `self.cfg['toolchainopts']`, and check whether the `phi` option is set to `True`, taking into account that it may not be set at all, something like `if self.cfg['toolchainopts'].get('phi', False)`.

Does that help?

**Comment by RalphTheBest** [comment]
It helps and more, since I think you solved all my problems with this issue. I'll test if I can have it working properly and if so, close the issue.
Thanks!

**Comment by RalphTheBest** [comment]
Indeed the `versionsuffix` was a life saver. I'm closing this now, I'll keep working on the phi support untill I'm sure is good enough for a PR.
Thanks for the help.
