### ISSUE TITLE
Can't install via bootstrapper script

### ISSUE THREAD

**Issue by eburgueno** [hpcugent/easybuild-framework#1804]
Hi, I'm trying to install easytools 2.8.1 in our cluster where we already use environment modules (Tcl) for some of the tools we provide.

The [bootstrap](http://easybuild.readthedocs.io/en/latest/Installation.html#bootstrapping-easybuild) script currently fails at STAGE 2 with the following traceback:
```
$ EASYBUILD_PREFIX=/<prefix path>/easybuild-2.8.1
$ python bootstrap_eb.py $EASYBUILD_PREFIX
[[INFO]] Installation prefix /<prefix path>/easybuild-2.8.1
[[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
[[INFO]] 
(...)
+++ STAGE 2: installing EasyBuild in /<MY_PREFIX>/easybuild-2.8.1 with EasyBuild from stage 1...

== temporary log file in case of crash /tmp/eb-wzg4zg/easybuild-mKcPfI.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 787, in <module>
    main()
  File "bootstrap_eb.py", line 590, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 508, in stage2
    easybuild_main()
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/main.py", line 255, in main
    modtool = modules_tool(testing=testing)
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 1126, in modules_tool
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 192, in __init__
    self.check_module_path()
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 379, in check_module_path
    self.prepend_module_path(eb_modpath)
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 360, in prepend_module_path
    self.add_module_path(path, set_mod_paths=set_mod_paths)
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 332, in add_module_path
    self.use(path)
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 317, in use
    self.run_module(['use', path])
  File "/tmp/tmpj6LFnx/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/modules.py", line 652, in run_module
    raise EasyBuildError(line)
easybuild.tools.build_log.EasyBuildError: "ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'use.own'"
```

`use.own` is a modulefile that comes with environment-modules and lives at `/usr/share`. It is loaded by default but unloading it before running the bootstrap script doesn't make any difference:
```
$ module show use.own
-------------------------------------------------------------------
/usr/share/Modules/modulefiles/use.own:

module-whatis	 adds your own modulefiles directory to MODULEPATH 
module		 use --append /home/<user>/privatemodules 
-------------------------------------------------------------------
```

Here's some environmental info:
```
$ python -V
Python 2.7.5
$ type module
module is a function
module () 
{ 
    eval `/usr/bin/modulecmd bash $*`
}
$ type -f module
-bash: type: module: not found
$ module --version
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/usr/share"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=undef
HAS_X11LIBS=1
LMSPLIT_SIZE=1000
MODULEPATH="/etc/modulefiles"
MODULES_INIT_DIR="/usr/share/Modules/init"
PREFIX="/usr/share/Modules"
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.13"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH=undef
WANTS_VERSIONING=0
WITH_DEBUG_INFO=undef

$ module av EasyBuild
$ which -a eb
/usr/bin/which: no eb in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/<user>/bin)
$ eb --version
-bash: eb: command not found
```

I tried using the alternative install method using `pip install --install-option "--prefix=...etc` , and this does complete. But after exporting `PATH` and `PYTHONPATH`, `eb --version` fails to run with an `ImportError: No module named vsc.utils` that looks suspiciously similar to #1204 (except I'm not using the development version install script).

**Comment by boegel** [comment]
@eburgueno The `use.own` module is known to be a problem in different types of situations (for example, with Lmod).

This is the first time it has come forward as a problem with EasyBuild, however...

Can you provide some more details on how and why `use.own` is loaded by default?

W.r.t. your attempt to installed EasyBuild directly via `pip`: that should work fine. Can you share how you defined `$PYTHONPATH`, and maybe also the output of this:

```
python -c "import sys; print sys.path; import vsc; print vsc.__file__; import vsc.utils; print vsc.utils.__file__"
```

**Comment by eburgueno** [comment]
@boegel 
> Can you provide some more details on how and why use.own is loaded by default?

Some users that want to help contributing their own modulefiles can test them before submitting a PR. For that, they add `module load use.own` to their `~/.modulerc`.

I did try doing `module unload use.own` before running the bootstrap script. Maybe this line in my `.modulerc` is causing issues? Looking at the script, `MODULEPATH` does get unset before STAGE 2, and this variable includes `/usr/share/Modules/modulefiles` by default (called in from `/etc/profile.d/modules.sh`, which calls `/usr/share/Modules/init/$shell`, which in turn populates `MODULEPATH` with the locations listed in `/usr/share/Modules/init/.modulespath`).

I'll try again after disabling my `~/.modulerc` and report back. I might open a different issue for the pip install one, so we can treat them separately.

**Comment by eburgueno** [comment]
Ok, confirmed. By removing `module load use.own` from my `~/.modulerc` the installation works.

I didn't test it, but I suspect that this is broader than just `use.own`. If you `unset MODULEPATH` in the bootstrap script, but `~./modulerc` was edited to load any other module, the installation might fail with a similar error.

**Comment by boegel** [comment]
@eburgueno OK, thank you for the update. I'll see whether hard resetting `$MODULEPATH` is actually strictly required, not doing so really the only way to fix this...

Do open a separate issue for the problems with `pip`, I'd like to figure that one out too.

**Comment by boegel** [comment]
@eburgueno I've patched the bootstrap script to no longer reset `$MODULEPATH` in stage 2, see https://github.com/hpcugent/easybuild-framework/pull/1810

Can you give this updated bootstrap script a try, with the `module use` in place in your `~/.modulerc`? You can grab it via https://raw.githubusercontent.com/boegel/easybuild-framework/bootstrap_no_reset_MODULEPATH/easybuild/scripts/bootstrap_eb.py while the pull request is still open.

**Comment by eburgueno** [comment]
Hi @boegel, I just did a quick try but I got a similar error. Here's what I found in the log file:
```
== 2016-06-14 19:50:23,341 filetools.py:905 INFO Creating directory /tmp/eb-sJ_g__/tmpF97FG2/tools/EasyBuild (parents: True, set_gid: False, sticky: False)
== 2016-06-14 19:50:23,360 environment.py:97 INFO Environment variable MODULEPATH set to /workspace/user/eb181/modules/all:/usr/share/Modules/modulefiles:/etc/modulefiles:/home/user/privatemodules (previous value: '/tmp/eb-sJ_g__/tmpF97FG2/all/:/workspace/user/eb181/modules/all:/usr/share/Modules/modulefiles:/etc/modulefiles:/home/user/privatemodules')
== 2016-06-14 19:50:23,442 build_log.py:152 ERROR ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'use.own' (at easybuild/tools/modules.py:652 in run_module)
== 2016-06-14 19:50:23,445 easyblock.py:2362 WARNING build failed (first 300 chars): ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'use.own'
```
It does look like `MODULEPATH` was set correctly this time though, so I'm not sure what's going on.

I can continue debugging tomorrow, is getting late in my timezone :)

**Comment by boegel** [comment]
@eburgueno Please try and collect a debug log, by defining `$EASYBUILD_BOOTSTRAP_DEBUG` before running the bootstrap script, that should give information

```
export EASYBUILD_BOOTSTRAP_DEBUG=1
```

**Comment by eburgueno** [comment]
Hi @boegel I tried running the bootstrap again with DEBUG enabled. I can't figure out what's wrong based on the output.

I've included both stdout and the build log in this file: [eb-bootstrap-debug.logs.tar.gz](https://github.com/hpcugent/easybuild-framework/files/322645/eb-bootstrap-debug.logs.tar.gz).

Please let me know if you need more information.

**Comment by boegel** [comment]
@eburgueno Thank you for the debug info, this helps.

The update to the bootstrap script to not unset `$MODULEPATH` is indeed there, but it proves to be insufficient.

During the `sanity_check_step`, EasyBuild tries to load a temporary version of the module file that will be generated. When doing this, it resets the (whole) environment to the starting state to ensure a 'clean' state to load the test module.

Afterwards, it 'resets' `$MODULEPATH` to ensure it has the right paths, in the right order. 'Resetting' here does **not** mean *clearing*  `$MODULEPATH`, but ensuring that the order of paths is restored as it should be (according to EasyBuild).
This basically boils down to restoring the original value of `$MODULEPATH` (with `/usr/share/Modules/modulefiles` included) and prepending the location where EasyBuild installs modules.

This is done by enforcing a prepend of each `$MODULEPATH` entry via a `module unuse`/`module use`, like this:

```
module use /home/user/privatemodules
module unuse /etc/modulefiles
module use /etc/modulefiles
module unuse /usr/share/Modules/modulefiles
module use /usr/share/Modules/modulefiles
```

The problem you're running into is that the 2nd-to-last `module unuse` command temporarily removes `/usr/share/Modules/modulefiles` from `$MODULEPATH`, which then leads to an error when running the last `module use`:

```
Unable to locate a modulefile for 'use.own'
```

So, it's the same problem, but it's being triggered differently...

I need to think about if and how this can be fixed. It may boil down to enhancing the logic in `check_module_path` in `easybuild/tools/modules.py` to avoid the `unuse/use` series of commands when the `$MODULEPATH` version after the reset is close to what it should be...

Thoughts?

**Comment by boegel** [comment]
@eburgueno I've worked out a possible fix in https://github.com/hpcugent/easybuild-framework/pull/1813, but it needs to be tested further.

Can you give this a try, as follows:

```
# set up tmpdir
mkdir /tmp/$USER/test1813
cd /tmp/$USER/1813

# download latest version of bootstrap script
curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py

# download tarballs for framework/easyblocks/easyconfigs to test with
curl -L https://github.com/boegel/easybuild-framework/archive/skip_unuse_use_check_module_path.tar.gz -o easybuild-framework-1813.tar.gz
curl -OL https://pypi.python.org/packages/93/7a/0d89cfde1530fc6932b9a474bd23808fef40ffcce03b99a7907700612371/easybuild-easyblocks-2.8.1.tar.gz
curl -OL https://pypi.python.org/packages/22/22/ecabee7c42a676a195301251bdc486c8b25fb4422963a0daab2184afed8f/easybuild-easyconfigs-2.8.1.tar.gz

# configure bootstrap to use tarball in current directory
export EASYBUILD_BOOTSTRAP_SOURCEPATH=$PWD

python bootstrap_eb.py $PWD
```

**Comment by eburgueno** [comment]
Hi @boegel, thanks for the explanation. I did notice the different `module unuse`|`module use`, but wasn't clear on why the need for them.

As I mentioned before, this is a consequence of having a `module load` in `~/.modulerc`. This happens in my environment, but there are several other RC files (and thus, modulefiles paths) that could trigger a similar error. [Here's the list](http://modules.sourceforge.net/man/module.html#lbAF).

You can't rely on `LOADEDMODULES` and compare with `module initlist` either, because the user may have changed the loaded modules during the shell session. Plus `initlist` doesn't output what's on the RC files.

Couldn't you restore `MODULEPATH` with a single command? `module use dir1 dir2 dirn`?

**Comment by eburgueno** [comment]
Ah we crossed comments. I'll try and test your new approach as soon as have time and report back.

**Comment by boegel** [comment]
@eburgueno I updated the instructions above, there were some issues with the previous list of commands, I noticed after testing them myself. Should be fine now, make sure you use the latest set of commands for testing the fix.

**Comment by eburgueno** [comment]
Hi @boegel , your instructions above worked just fine. Happy with this one now.

I'll double check the pip route and report back on a new issue. Thanks for your help!

**Comment by boegel** [comment]
@eburgueno Thanks for the confirmation! #1813 is merged, so I will close this issue; please do open another issue if you're still seeing the `pip` issues
