### ISSUE TITLE
Support for organizations in github integration 

### ISSUE THREAD

**Issue by timeu** [hpcugent/easybuild-framework#1890]
We have an organization for our institute that has a forked repo of `easybuild-easyconfig`
It would be handy if organizations were supported in the github integration (for submitting pull requests, etc). 
Currently the remote repo url is constructed using the `github-user` setting (see this [line](https://github.com/hpcugent/easybuild-framework/blob/f3f324ab6c872cbcabd18fb257a0a68f5a20d49a/easybuild/tools/github.py#L885)). 
It would be nice to be able to override the remote url (maybe through a flag). 

I can do a pull-request for that feature.

**Comment by boegel** [comment]
@timeu that would certainly be useful, let me know if you need any help with this!

**Comment by timeu** [comment]
@boegel : thanks, I would branch out from the develop branch and implement the feature in https://github.com/hpcugent/easybuild-framework/blob/develop/easybuild/tools/github.py and add a test or update an existing one in https://github.com/hpcugent/easybuild-framework/blob/develop/test/framework/github.py. 

What's the easiest way to setup a local development installation of easybuild-framework ? Should I just checkout develop branch of easybuild-framework ?

**Comment by boegel** [comment]
@timeu you will also need to add an option in `easybuild/tools/options.py`, and likely also list the new option in `easybuild/tools/config.py` to make it a *build option* (cfr. use of `build_option`)

Checking out the `develop` branch is indeed the proper way to set up a development environment, together with updating `$PATH` and `$PYTHONPATH` to point to that location. For information on running the unit tests, see http://easybuild.readthedocs.io/en/latest/Unit-tests.html .

**Comment by boegel** [comment]
fixed in #1894, thanks @timeu!
