### ISSUE TITLE
Disabling MPI testing

### ISSUE THREAD

**Issue by jhein32** [hpcugent/easybuild-framework#1906]
A number of easy-configs start MPI tests.  Depending on environment this can create issues and prevents the module from being build.  A command-line option to disable MPI testing would be useful.  

EB-users would (should) know that stuff is not properly tested and would need to resort to some other tests.  But at least this way they get executables and modules for further testing.

**Comment by boegel** [comment]
support for `--disable-mpi-tests` is added in #1920, easyblocks are updated to take it into account in https://github.com/hpcugent/easybuild-easyblocks/pull/993, let's follow up there
