### ISSUE TITLE
problem with --dry-run and dependencies

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1922]
Hi,

It seems that the dependency resolution is not working properly when using the `--dry-run` option. I am getting this error:

```
[easybuild@login18 easyconfigs]$ eb-test Python-3.5.2-foss-2016b.eb -r . -D --debug
== temporary log file in case of crash /scratch/eb-kykuPb/easybuild-XKoj9y.log
ERROR: Irresolvable dependencies encountered: XZ/5.2.2-goolf-1.7.20
```

but the module is availabe, I can see it if I do `module show XZ/5.2.2-goolf-1.7.20` and I can load it doing `ml XZ/5.2.2-goolf-1.7.20`

If I try the same command line without the `--dry-run` option the installation works fine.

I have uploaded a debug log here:
https://gist.github.com/anonymous/b3e7b0186f67bf01b575989cba27e312

**Comment by boegel** [comment]
@pescobar for a dry-run, all *easyconfigs* need to be available, since the module name to check for is determined via the easyconfig (you could be using a custom module naming scheme)

It seems like you don't have the easyconfig for XZ 5.2.2 with `goolf/1.7.20` in your robot search path?

**Comment by pescobar** [comment]
ups, you are right, I totally forgot this. Pointing the robot search path to my easyconfigs repository it works fine.

Thanks for you help. I think this issue can be closed.
