### ISSUE TITLE
Saved `.eb` file cannot reproduce build when list of configopts was used

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-framework#1939]
Take for example, the `ncurses-6.0.eb` easyconfig (some irrelevant parts omitted)::

    easyblock = 'ConfigureMake'

    name = 'ncurses'
    version = '6.0'

    # ...

    configopts = [
        # default build
        '--with-shared --enable-overwrite',
        # the UTF-8 enabled version (ncursesw)
        '--with-shared --enable-overwrite --enable-ext-colors --enable-widec --includedir=%(installdir)s/include/ncursesw/'
    ]

    libs = ["form", "menu", "ncurses", "panel"]
    sanity_check_paths = {
        'files': ['bin/%s' % x for x in ["captoinfo", "clear", "infocmp", "infotocap", "ncurses%(version_major)s-config",
                                         "reset", "tabs", "tic", "toe", "tput", "tset"]] +
                 ['lib/lib%s%s.a' % (x, y) for x in libs for y in ['', '_g', 'w', 'w_g']] +
                 ['lib/lib%s%s.%s' % (x, y, SHLIB_EXT) for x in libs for y in ['', 'w']] +
                 ['lib/libncurses++%s.a' % x for x in ['', 'w']],
        'dirs': ['include', 'include/ncursesw'],
    }

    moduleclass = 'devel'

Now run EB and build it successfully::

    $ eb -l ncurses-6.0.eb
    [...]
    == 2016-09-30 13:25:03 build_log.py:238 INFO Build succeeded for 1 out of 1
    == Build succeeded for 1 out of 1
    == Temporary directory /tmp/eb-_U6GSv has been removed.

However, the `.eb` file saved in the "repositorypath" and also in the `reprod/`
subdirectory cannot properly reproduce the build. Any attempt to use it will
only build the `ncursesw` part of the package (and thus fail the sanity check)::

    $ cat ncurses-6.0.eb
    # Built with EasyBuild version 2.9.0 on 2016-09-30_13-25-03
    easyblock = 'ConfigureMake'

    name = 'ncurses'
    version = '6.0'

    homepage = 'http://www.gnu.org/software/ncurses/'
    description = """The Ncurses (new curses) library is a free software emulation of curses in System V Release 4.0,
     and more. It uses Terminfo format, supports pads and color and multiple highlights and forms characters and
     function-key mapping, and has all the other SYSV-curses enhancements over BSD Curses."""

    toolchain = {'version': 'dummy', 'name': 'dummy'}
    toolchainopts = {'optarch': True, 'pic': True}

    sources = [SOURCE_TAR_GZ]
    source_urls = [GNU_SOURCE]

    patches = ['%(name)s-mawk.patch']

    configopts = "--with-shared --enable-overwrite --enable-ext-colors --enable-widec --includedir=%(installdir)s/include/ncursesw/"

    parallel = 1

    unwanted_env_vars = {}
    start_dir = '%(builddir)s/%(name)s-%(version)s/'

    sanity_check_paths = {
        'files': ['bin/captoinfo', 'bin/clear', 'bin/infocmp', 'bin/infotocap', 'bin/%(name)s%(version_major)s-config', 'bin/reset', 'bin/tabs', 'bin/tic', 'bin/toe', 'bin/tput', 'bin/tset', 'lib/libform.a', 'lib/libform_g.a', 'lib/libformw.a', 'lib/libformw_g.a', 'lib/libmenu.a', 'lib/libmenu_g.a', 'lib/libmenuw.a', 'lib/libmenuw_g.a', 'lib/libncurses.a', 'lib/libncurses_g.a', 'lib/libncursesw.a', 'lib/libncursesw_g.a', 'lib/libpanel.a', 'lib/libpanel_g.a', 'lib/libpanelw.a', 'lib/libpanelw_g.a', 'lib/libform.so', 'lib/libformw.so', 'lib/libmenu.so', 'lib/libmenuw.so', 'lib/libncurses.so', 'lib/libncursesw.so', 'lib/libpanel.so', 'lib/libpanelw.so', 'lib/libncurses++.a', 'lib/libncurses++w.a'],
        'dirs': ['include', 'include/ncursesw'],
    }  # the UTF-8 enabled version (ncursesw)

    moduleclass = 'devel'

The list part of `configopts` has been lost in the process and only the last string value used has been saved.

**Comment by boegel** [comment]
@riccardomurri it seems that this issue can only present itself when `--minimal-toolchains` is used, can you confirm that was the case for you @riccardomurri? Can you provide the output of `eb --show-config` in the setup where you can reproduce this issue?

**Comment by boegel** [comment]
@riccardomurri I was able to reproduce this, but only under `--minimal-toolchains` (in which case the easyconfig is being dumped differently)

Should be fixed with #1949

**Comment by riccardomurri** [comment]
Yes, I have `--minimal-toolchains` in effect.

**Comment by boegel** [comment]
OK, then #1949 fixes this bug, thanks for reporting it @riccardomurri!
