### ISSUE TITLE
Bootstrapping 2.9.0 fails

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild-framework#1945]
I'm having trouble bootstrapping 2.9.0 on my SLSE box:

    $ python --version
    Python 2.7.9
    $ python -c 'import setuptools; print(setuptools.__version__)'
    26.1.1

    $ export EASYBUILD_PREFIX=$HOME/eb

    $ curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py

    $ python bootstrap_eb.py $EASYBUILD_PREFIX
    [[INFO]] Installation prefix /home/hilboll/eb
    [[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
    [[INFO]] 
    
    +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...
    
    
    Downloading http://hpcugent.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
    Extracting in /tmp/hilboll/tmp4MKkia
    Now working in /tmp/hilboll/tmp4MKkia/distribute-0.6.49
    Installing Distribute
    [[INFO]] 
    
    +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...
    
    
    [[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/hilboll/tmp1pNJ2S/eb_stage1 easybuild'
    Installing with setuptools.setup...
    Installing version 2.9.0
    warning: install_lib: 'build/lib' does not exist -- no Python modules to install
    
    zip_safe flag not set; analyzing archive contents...
    Installing with setuptools.setup...
    Installing version 2.9.0 (API version 2)
    Installing with setuptools.setup...
    Installing version 2.9.0 (required versions: API >= 2)
    Installing with setuptools.setup...
    Installing version 2.9.0 (required versions: API >= 2, easyblocks >= 2.9)
    warning: install_lib: 'build/lib' does not exist -- no Python modules to install
    
    INFO: This is (based on) vsc.install.shared_setup 0.10.14
    INFO: run_tests from base dir /tmp/hilboll/easy_install-bh2Ko2/vsc-base-2.5.4 (using executable /tmp/hilboll/easy_install-bh2Ko2/vsc-base-2.5.4/setup.py)
    WARN: cleanup lib/vsc_base.egg-info
    INFO: initial packages list: ['vsc', 'vsc.utils']
    INFO: generated list: ['vsc', 'vsc.utils']
    INFO: generated packages list: ['vsc', 'vsc.utils']
    INFO: makesetupcfg set to True, (re)creating setup.cfg
    INFO: found license /tmp/hilboll/easy_install-bh2Ko2/vsc-base-2.5.4/LICENSE with md5sum 5f30f0716dfdd0d91eb439ebec522ec2
    INFO: Found license name LGPLv2+ and classifier License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
    INFO: setting license LGPLv2+
    INFO: No name defined, trying to determine it
    INFO: found match url https://github.com/hpcugent/vsc-base in /tmp/hilboll/easy_install-bh2Ko2/vsc-base-2.5.4/PKG-INFO
    INFO: found match name vsc-base in /tmp/hilboll/easy_install-bh2Ko2/vsc-base-2.5.4/PKG-INFO
    INFO: Removing None download_url
    INFO: get_name_url returns {'url': 'https://github.com/hpcugent/vsc-base', 'name': 'vsc-base'}
    INFO: using long_description Common tools used within our organization. Originally created by the HPC team of Ghent University (http://ugent.be/hpc).
    INFO: generated list: ['bin/optcomplete.bash', 'bin/logdaemon.py', 'bin/startlogdaemon.sh']
    INFO: generated scripts list: ['bin/optcomplete.bash', 'bin/logdaemon.py', 'bin/startlogdaemon.sh']
    INFO: adding prospector to tests_require
    WARN: zip_safe flag not set; analyzing archive contents...
    WARN: vsc.utils.fancylogger: module MAY be using inspect.stack
    WARN: vsc.utils.exceptions: module MAY be using inspect.getouterframes
    WARN: vsc.utils.generaloption: module MAY be using inspect.stack
    [[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/hilboll/tmp1pNJ2S/eb_stage1 vsc-base'
    INFO: Searching for vsc-base
    INFO: Reading http://pypi.python.org/simple/vsc-base/
    INFO: Best match: vsc-base 2.5.4
    INFO: Processing vsc_base-2.5.4-py2.7.egg
    INFO: vsc-base 2.5.4 is already the active version in easy-install.pth
    INFO: Installing startlogdaemon script to /tmp/hilboll/tmp1pNJ2S/eb_stage1/bin
    INFO: Installing optcomplete.bash script to /tmp/hilboll/tmp1pNJ2S/eb_stage1/bin
    INFO: Installing logdaemon script to /tmp/hilboll/tmp1pNJ2S/eb_stage1/bin
    INFO: 
    Using /tmp/hilboll/tmp1pNJ2S/eb_stage1/lib/python2.7/site-packages/vsc_base-2.5.4-py2.7.egg
    INFO: Processing dependencies for vsc-base
    INFO: Finished processing dependencies for vsc-base
    [[INFO]] 
    
    +++ STAGE 2: installing EasyBuild in /home/hilboll/eb with EasyBuild from stage 1...
    
    
    Traceback (most recent call last):
      File "bootstrap_eb.py", line 793, in <module>
        main()
      File "bootstrap_eb.py", line 596, in main
        stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
      File "bootstrap_eb.py", line 513, in stage2
        from easybuild.main import main as easybuild_main
      File "/tmp/hilboll/tmp1pNJ2S/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/main.py", line 47, in <module>
        from easybuild.tools.build_log import EasyBuildError, init_logging, print_msg, print_error, stop_logging
      File "/tmp/hilboll/tmp1pNJ2S/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/tools/build_log.py", line 200, in <module>
        def init_logging(logfile, logtostdout=False, silent=False, colorize=fancylogger.Colorize.AUTO):
    AttributeError: 'module' object has no attribute 'Colorize'

**Comment by boegel** [comment]
@andreas-h it seems like you have an old version of `vsc-base` installed that is picked up, over the one that was installed in 'stage 1' of the bootstrap procedure...

Python is pretty nasty this way, taking control of `$PYTHONPATH` is not sufficient to be in control.

Can you check what this prints?

```shell
$ python -c "import vsc; print vsc.__file__"
$ python -c "import vsc.fancylogger; print vsc.fancylogger.__file__"
```

**Comment by andreas-h** [comment]
Thanks, Kenneth, I indeed had an old install of vsc in `$HOME/.local`.
After removing that, bootstrapping works as advertised.

**Comment by boegel** [comment]
@andreas-h that location, together with system-wide locations like `/usr/lib` are 'magic', in the sense that they are considered prior to what `$PYTHONPATH` specifies...

It's hard to avoid this, but the bootstrap script could/should check for this and emit a clear error message. I'll see what I can do to put that in place.
