### ISSUE TITLE
tools/toolchain/compiler.py _set_compiler_flags should use nextend instead of nappend when setting the actual C/F FLAGS

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-framework#1967]
If there is a option that isn't a simple string but multiple flags the use of
self.variables.nappend(var, flags) results in things like
-fPIC -['someflag', 'flag2']

Using
self.variables.nextend(var, flags)
instead gives the expected result of
-fPIC -someflag -flag2

Opened PR 1966 for this

**Comment by boegel** [comment]
fixed in #1966, thanks @akesandgren
