### ISSUE TITLE
ModuleCmd_Load.c(200):ERROR

### ISSUE THREAD

**Issue by hjateni** [hpcugent/easybuild-framework#1990]
Error: unable to use 'modulecmd' of Lmod and also after system reboot, eb and module commands doesn't exist that means , we need to install again

**Comment by boegel** [comment]
To make the `eb` command available, you need to add the location of the `eb` command to the `$PATH` environment variable.

If you installed EasyBuild to `/some/location`, you need to run:

```
export PATH=/some/location/bin:$PATH
```

For the `module` command, you need to `source` the init script that comes with it, for example (if you installed Lmod to `$HOME`):

```
source $HOME/lmod/lmod/init/bash
```

You can/should put both the `export PATH=...` and `source .../init/bash` commands in your `.bashrc` startup script.
