### ISSUE TITLE
installed easyconfig won't be saved to repository if the easyconfig contains build stats

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#1996]
I have noticed that when installing some of my previous easyconfigs they were not pushed to the git repository where I save all my installed easyconfigs. 

After some testing I found out that if the installed easyconfig contains `buildstats` then it's not pushed to git (I haven't checked if this is the case when using a local folder as repository instead of git)

As example, if you install this easyconfig it will be saved to the git repo:
https://gist.github.com/1836bbc77cbf87693805a56c472bf11e

If you install this easyconfig it won't be saved to the git repo:
https://gist.github.com/1b8671aa5234e01e3f37e83075d9cd79

I couldn't find any useful info in the debug log about why this is happening. I found it by try&error. Is this a bug or feature? ;)

Personally I would like that every installed easyconfig is always pushed to my git repository.

**Comment by boegel** [comment]
@pescobar I believe this is fixed with #1948, it sure looks like the same problem

**Comment by boegel** [comment]
@pescobar please check whether you're still seeing this with EasyBuild v3.0.0?

**Comment by pescobar** [comment]
@boegel I just verified that this issue is solved in v3.0 so closing this issue

**Comment by boegel** [comment]
Great, thanks @pescobar!
