### ISSUE TITLE
add support for packaging software builds, e.g. into RPMs

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#200]
It would be nice if EasyBuild is able to generate packaged builds of software, e.g. RPMs or .deb files.

When a command line option ```--package=rpm``` (for example) is passed, EasyBuild should package the built software as an RPM, which can then be distributed.

Implementing this should be done in a modular way, so support for new types of packages can be easily plugged into EasyBuild by simply implementing a new class that derives from an abstract class ```Package```, e.g. ```RPMPackage``` or ```DebPackage```.

This would significantly expand the possible use cases for EasyBuild.

**Comment by rjeschmi** [comment]
Just to update this issue,

a first crack went into #1170

**Comment by rjeschmi** [comment]
A link to an interesting example of a SPEC file from TACC

https://github.com/hpcugent/easybuild-easyconfigs/pull/418#issuecomment-45843539

**Comment by rjeschmi** [comment]
This should be closed I think.

**Comment by fgeorgatos** [comment]
@boegel: please close this

**Comment by boegel** [comment]
Packaging support is stable since EasyBuild v2.5.0, see also http://easybuild.readthedocs.org/en/latest/Packaging_support.html
