### ISSUE TITLE
rpath's sanity check crashes when building numpy

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#2009]
while doing my first test with rpath I have found that the sanity check in rpath crashes when building numpy. This is the error message:

`AttributeError: 'EB_numpy' object has no attribute 'modules_tool'`

This is the full debug log:
https://gist.github.com/anonymous/41ce31fd5419b76a3a9b03135adc1578

**Comment by pescobar** [comment]
in case this makes any difference, I am not getting this error when building a numpy easyconfig. I get the error when building a python easyconfig which includes numpy in the extensions list.

**Comment by boegel** [comment]
@pescobar it does make a different, `EB_numpy` inherits both from `EasyBlock` and `Extension`, and apparently in the latter case something is broken, but only when `--rpath` is used, which is kind of weird...

**Comment by boegel** [comment]
fixed in #2026, kind of a silly bug...
