### ISSUE TITLE
output of sanity_check_comands is not added to the build log unless --debug is used

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#2018]
I have noticed that the output of `sanity_check_comands` is not added to the build log unless I use `--debug`

I think it would be nice that this is added by default to the build log. Is there any reason to skip it?

**Comment by boegel** [comment]
@pescobar not really, but this is trivial to fix by changing the `log.debug` to `log.info` in https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/framework/easyblock.py#L2040

**Comment by pescobar** [comment]
is there any reason against doing this change?

**Comment by boegel** [comment]
@pescobar definitely not, I'm waiting for a PR from you ;)

**Comment by pescobar** [comment]
here you have ;) https://github.com/hpcugent/easybuild-framework/pull/2020

**Comment by boegel** [comment]
follow-up in #2020
