### ISSUE TITLE
easybuild install and test

### ISSUE THREAD

**Issue by umccs** [hpcugent/easybuild-framework#2029]
Hello,

I'm having trouble with the test.framework.suite script.  I get "......................Skipping test_######, no GitHub token available?" messages.  Any idea what is going on.  I was able to get the "eb --check-github" command to return "all checks passed".  I have also forked the easybuild-configs to my git account.

Best,
Pedro 
$ eb --check-github --git-working-dirs-path /scratch/pedro/easybuild/git-working-dirs
== temporary log file in case of crash /tmp/eb-56Hpfc/easybuild-5IXmie.log

Checking status of GitHub integration...

Making sure we're online... OK

* GitHub user... umccs => OK
* GitHub token... d7c..668 (len: 40) => OK (validated)
* git command... OK ("git version 1.8.3.1; ")
* GitPython module... OK (GitPython version 1.0.1)
* push access to umccs/easybuild-easyconfigs repo @ GitHub... OK
* creating gists... OK
* location to Git working dirs...  OK (/scratch/pedro/easybuild/git-working-dirs)

All checks PASSed!

Status of GitHub integration:
* --from-pr: OK
* --new-pr: OK
* --review-pr: OK
* --update-pr: OK
* --upload-test-report: OK

[pedro@eg01 ~]$ python -m vim 
INFO: This is (based on) vsc.install.shared_setup 0.10.20

Running tests...
----------------------------------------------------------------------
......................Skipping test_empty_pr, no GitHub token available?

**Comment by boegel** [comment]
@umccs to also run the GitHub tests, a token must be available for the (fictive) GitHub account `easybuild_test`

If you install a token for `easybuild_test` (using `eb --install-github-token`, http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#installing-a-github-token-install-github-token), the tests that require a token should not be skipped.

Note that you can just create a new token using your own GitHub account, and register it as if it were a token for `easybuild_test`; the login name doesn't matter anymore once you have a token.

If this solves your problem/answers your question, please close this issue.

**Comment by surak** [comment]
> Note that you can just create a new token using your own GitHub account, and register it as if it were a token for `easybuild_test`; the login name doesn't matter anymore once you have a token.

It will fail at "pythom -m test.framework.suite" :

```
eb --github-user surak --force  --install-github-token
== temporary log file in case of crash /tmp/eb-fgt3i5/easybuild-HAqPrY.log
Please enter password for encrypted keyring: 
WARNING: overwriting installed token '236..77d' for user 'surak'...
Token: 
Validating token...
Token seems to be valid, installing it.
Token 'e29..cee' installed!
a.strube@zam347:~$ python -m test.framework.suite
INFO: This is (based on) vsc.install.shared_setup 0.11.3

Running tests...
----------------------------------------------------------------------
...............................Skipping test_empty_pr, no GitHub token available?

```
