### ISSUE TITLE
rpath sanity check crashes when installing intel mpi

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#2053]
Here you have the build log:
https://github.com/hpcugent/easybuild-framework/pull/2052#issuecomment-266199664

I guess this will be solved by this one? https://github.com/hpcugent/easybuild-easyblocks/pull/1056/commits/32c8faf8ad442fc2579b553047aaf3758bab2360

**Comment by pescobar** [comment]
I just verified this is solved in develop. closing.

**Comment by boegel** [comment]
yes, skipping the sanity check in `IntelBase` indeed fixes this
