### ISSUE TITLE
POWER: `--optarch=GENERIC` broken for GCC

### ISSUE THREAD

**Issue by geimer** [hpcugent/easybuild-framework#2064]
While working on https://github.com/hpcugent/easybuild-framework/pull/1974, I noticed that `--optarch=GENERIC` is broken for GCC on POWER, as it passes an unknown value (`generic-arch`) to the `-mcpu=` compiler option.  It seems like the following are suitable candidates instead (quote from the GCC manual):

> -mcpu=powerpc, -mcpu=powerpc64, and -mcpu=powerpc64le specify pure 32-bit PowerPC (either endian), 64-bit big endian PowerPC and 64-bit little endian PowerPC architecture machine types, with an appropriate, generic processor model assumed for scheduling purposes.

As far as I can see, `powerpc64le` is supported since GCC 4.8, the other two were already available in the 3.x series.  However, this means that we have to distinguish between big and little endian POWER (with everything up to POWER7 being big endian and POWER8 being little endian).  I suggest to indicate the endianess via the CPU family (i.e., architecture is `POWER` in both cases, but family may be either `POWER_BE` or `POWER_LE`).

**Comment by geimer** [comment]
Or better stick to `POWER` for big-endian (for backward compatibility) and introduce `POWER_LE` for little-endian.

**Comment by boegel** [comment]
@geimer fixed in #2073, so let's close this and follow up in there?
