### ISSUE TITLE
RFF: option to dump modules during build

### ISSUE THREAD

**Issue by JackPerdue** [hpcugent/easybuild-framework#2108]
A construct I use quite a bit while trying to write new EasyConfigs is:

preconfigopts = """
    MFILE='/tmp/mods-%(name)s-%(version)s-%(toolchain_name)s-%(toolchain_version)s'
    module -t list >& $MFILE
    cat $MFILE
"""

Just so I have a quick list of modules to load.  I know similar can be obtained (with effort) with --dump-env-script but having them listed in the final build log is handy as well.

Again, I have PayPal beer money to throw around (see previous issue).

**Comment by boegel** [comment]
@JackPerdue You can obtain exactly this via `--extended-dry-run`, see http://easybuild.readthedocs.io/en/latest/Extended_dry_run.html#module-load-statements-are-executed-or-simulated ?

**Comment by JackPerdue** [comment]
When the heck did that get added?  That looks entirely too useful.   :)   I owe somebody a beer.
