### ISSUE TITLE
Order in known_module_commands

### ISSUE THREAD

**Issue by koallen** [hpcugent/easybuild-framework#2119]
Hi, I have a question regarding the order of module tools in the variable `known_module_commands`. To my knowledge, EasyBuild works the best together with Lmod since Lmod has some cool new features such as module hierarchy. However, the order when checking module command installed on the system is

```python
# order matters, which is why we don't use a dict
known_module_commands = [
    ('modulecmd', 'EnvironmentModulesC'),
    ('lmod', 'Lmod'),
    ('modulecmd.tcl', 'EnvironmentModulesTcl'),
]
```

Shouldn't it check Lmod first before the old Environment Module tool?

**Comment by boegel** [comment]
Good point, thanks for raising this @koallen!

Fixed in #2201
