### ISSUE TITLE
multiple paths in include-easyblocks doesn't always work

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-framework#2150]
Having
```
include-easyblocks=/home/a/ake/Public/easybuild/easyblocks/*.py
,/hpc2n/eb/custom/easyblocks/*.py
```
in my config file fails if the same easyblock is present in both directories.
```
eb --show-config
ERROR: Failed to parse configuration options: 'Symlinking /hpc2n/eb/custom/easyblocks/siesta.py to /scratch/eb-yAoV90/included-easyblocks/easybuild/easyblocks/siesta.py failed: [Errno 17] File exists'
```

This makes it harder to keep on developing an easyblock that haven't been accepted upstreams yet but is good enough for a site to move forward. The framework should handle this in my opinion. First seen should take precedence.

**Comment by boegel** [comment]
fixed in #2151, let's follow up there
