### ISSUE TITLE
optarch for different compilers breaks --job

### ISSUE THREAD

**Issue by mstud** [hpcugent/easybuild-framework#2182]
I was trying to use the GC3Pie job backend but keep getting this error message in the job log file:

ERROR: Failed to parse configuration options: "The optarch option has an incorrect syntax: '{\\'GCC\\': \\'march=westmere -mtune=haswell\\', \\'Intel\\': \\'xSSE4.2 -axCORE-AVX2\\'}'"

My optarch line in the EasyBuild config file:
optarch=Intel:xSSE4.2 -axCORE-AVX2;GCC:march=westmere -mtune=haswell

It works fine without --job. Looks like the rather new feature that lets us set optarch per compiler somehow breaks when being used in conjunction with the --job feature. Or am I doing something wrong?

**Comment by boegel** [comment]
@damianam Any ideas on this one?

**Comment by damianam** [comment]
I haven't tested the option using a config file, but in a terminal I'd put the options between single quotes. However, the error seems to spit a valid dictionary.......

The troubled lines are these: https://github.com/hpcugent/easybuild-framework/blob/261861679742a8cc69cca232bb878bd698cd93f7/easybuild/tools/options.py#L745 but I don't see how that can happen...... I'll try to take a look at it tomorrow, sadly I can't do it now.

**Comment by Sneeg** [comment]
The problem seems to be that _postprocess_optarch is called twice when using --job, once immediately when running eb and then later in the job again. The second time, self.options.optarch has already been overwritten by the string representation of the dictionary with the parsed data. Then,  of course, there is no OPTARCH_SEP in the string, but two OPTARCH_MAP_CHARs, so the exception is raised.

**Comment by damianam** [comment]
I'd say you are right, but there is more to it. `self.options.optarch` is a string that looks like an already processed `dict`, and that's why it doesn't fail during `self.options.optarch.split(OPTARCH_SEP)`

I think the issue is more complex than it looks like because somewhere, when using `--job`, the `dict` gets serialized to a string, and then things go down. We could apply a quick and dirty fix here to check if the `optarch` string looks like a `dict`, but in my opinion we should treat the "illness", not the "symptom"

**Comment by damianam** [comment]
> but in my opinion we should treat the "illness", not the "symptom"

On the other hand, this can be seen as a side effect of doing something nasty, like shoving a dict into what it used to be a string. I remember saying something like "I am not convinced that's a great idea...." ;-P. Maybe it is better to simply check if `--job` is part of the options, and avoid the processing altogether when that happens?

**Comment by boegel** [comment]
@damianam We should look into how hard it is to avoid changing `options.optarch` in place, since that would fix the problem, no?

Alternatively, we can treat `--optarch` specially when passing down options to the submitted job, if we have to, but I'd consider that a last resort.

**Comment by damianam** [comment]
@boegel I assume you didn't read my last reply. A third way would be to avoid processing the option the first time, and leave the parsing to the second pass, once `--job` is removed and the job is running on the node. This should be fairly easy to implement.

Avoid changing `options.optarch` is also perfectly feasible, but requires deciding where to put the dict, or generate the dict on the fly (which in turn requires calling the processing option from the toolchain, which I find a bit weird). That will also imply important changes in the tests, and I won't have much time to do deep changes during the next few weeks.

**Comment by boegel** [comment]
@damianam Skipping the parsing under `--job` makes sense too, indeed.

**Comment by damianam** [comment]
Just pick your fix and I'll implement it. But keep in mind that one can be done today, and the other will have to wait, there are too many things in my TODO list with high priority ;-)

**Comment by boegel** [comment]
@damianam Go with your suggestion, postponing the parsing, makes sense to me.

**Comment by damianam** [comment]
@mstud could try out the fix in https://github.com/hpcugent/easybuild-framework/pull/2183 ?

**Comment by mstud** [comment]
Works like a charm, thank you for the prompt fix.

**Comment by mstud** [comment]
Was bit fast to close this here, while it does indeed not prevent me from using --job anymore, it seems to ignore the optarch in a job now altogether:

== 2017-03-29 08:28:49,711 environment.py:97 INFO Environment variable OPTFLAGS set to -O3 -xHost (previously undefined)

**Comment by mstud** [comment]
If it helps you debug the issue, it appears that in the job there have been single quotes added to the self.options.optarch string which messes up the parsing.

**Comment by boegel** [comment]
let's follow up on this in #2183, I don't like having two 'issues' open for the same problem, it's confusing
