### ISSUE TITLE
bad behaviour in framework/easyconfig/easyconfig.py update function

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-framework#2189]
The class EasyConfig update function is incorrectly adding an extra " " when updating strings.

```
    def update(self, key, value):
        """
        Update a string configuration value with a value (i.e. append to it).
        """
        prev_value = self[key]
        if isinstance(prev_value, basestring):
            self[key] = '%s %s ' % (prev_value, value)
        elif isinstance(prev_value, list):
            self[key] = prev_value + value
        else:
            raise EasyBuildError("Can't update configuration value for %s, because it's not a string or list.", key)
```
The "self[key] = '%s %s ' % (prev_value, value)" should not contain the last " "
This is currently causing problems with my current update to the NAMD easyblock.

With the current code i get a double " " in the string which is causing trouble later on in the NAMD easyblock.

**Comment by akesandgren** [comment]
See PR #2190

**Comment by boegel** [comment]
follow-up in #2190
