### ISSUE TITLE
In filetools.py, max_fail_ratio=0.5 should be a tunable?

### ISSUE THREAD

**Issue by fgeorgatos** [hpcugent/easybuild-framework#2212]
ref. https://github.com/hpcugent/easybuild-framework/search?utf8=%E2%9C%93&q=max_fail_ratio&type=

In `filetools.py`, `max_fail_ratio` should be a tunable?
N.B. we've got a filesystem export which gives complaints (only that export), however I believe that as a performance tradeoff since I otherwise do not detect any side-effect. So, could this be ignored, at will?!

```
    fail_ratio = fail_cnt / float(len(allpaths))
992	    max_fail_ratio = 0.5
993	    if fail_ratio > max_fail_ratio:
994	        raise EasyBuildError("%.2f%% of permissions/owner operations failed (more than %.2f%%), "
…	
995	                             "something must be wrong...", 100 * fail_ratio, 100 * max_fail_ratio)
996	    elif fail_cnt > 0:
997	        _log.debug("%.2f%% of permissions/owner operations failed, ignoring that..." % (100 * fail_ratio))
```

**Comment by boegel** [comment]
This should indeed be configurable, hardcoded values are invented by the devil himself.

Fixed in #2213
