### ISSUE TITLE
GNU_SOURCE constant points to wrong URL

### ISSUE THREAD

**Issue by rcespa** [hpcugent/easybuild-framework#2233]
Good day to everyone.
First of all let me say that I am a complete noob to easybuild but I really want to say a big thank you to everyone involved in its development.

I was trying to install some modules but I often hit the wall of "_Couldn't find file XXXXX anywhere and downloading id didn't work either_" error message; taking a look at the logs I noticed that the URL used to download packages from gnu.org is always http://ftpmirror.gnu.org/PACKAGENAME and this is the value of the GNU_SOURCE constant; when I tried to open these URLs from my browser I always got a 404 error independently by the mirror used; then I realized that the correct format should be http://ftpmirror.gnu.org/gnu/PACKAGENAME (eg.: http://ftpmirror.gnu.org/ncurses/ncurses-6.0.tar.gz should read http://ftpmirror.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz )

I ran this "oneliner":

`for i in $(grep -r -l ftpmirror.gnu.org\/ * | grep .eb$ ); do cat $i | sed s/ftpmirror.gnu.org/ftpmirror.gnu.org\\/gnu/g > $i.rc; mv -v $i.rc $i; done`

to update all the .eb files with hardcoded URLs and I edited 
`easybuild_framework-3.2.1-py2.6.egg/easybuild/framework/easyconfig/templates.py`
to update the constant.

Unfortunately some mirrors does not handle correctly the redirect and this can be solved setting the URL to ftp.gnu.org instead of ftpmirror.gnu.org .

I was wondering if this was the right way to solve the problem or if exists a simple configuration option (command line or file) to override the default settings.

Ciao,
Roberto

**Comment by boegel** [comment]
@rcespa Thank you very much for the bug report!

It seems like you're hitting the nail on the head, and I guess this explains why we've been seeing problematic downloads for GNU software, but only occasionally (something it seems to work without the `/gnu`, depending on which mirror is being used)...

Fixed in https://github.com/hpcugent/easybuild-framework/pull/2235 & https://github.com/hpcugent/easybuild-easyconfigs/pull/4653.

**Comment by rcespa** [comment]
Sometimes I have problems with ftp.gnu.org and github, too.
It looks like a timeout problem because I'm able to download the problematic tar.gz files manually via wget; when I do this, I can see the transfer speed dropping at the end and stalling for some seconds.

**Comment by boegel** [comment]
@rcespa You can use the `--download-timeout` option available in `eb` to specify a larger timeout threshold (default is 10 seconds)

**Comment by rcespa** [comment]
I'll give it a try! Thanks

**Comment by robqiao** [comment]
Same issue here, seems --download-timeout=30 some times fix the timeout, hard code the URL seems working most of times for me.

**Comment by boegel** [comment]
@robqiao Can you clarify what you mean with "hard code the URL"?

**Comment by robqiao** [comment]
@boegel rather than use <code>GNU_SOURCE</code> system variable, use the URL directly, something like this <code>source_urls = ['ftp://ftp.gnutls.org/%(account)s/%(name)s/v%(version_major_minor)s']</code> works fine even time I had this issue.

**Comment by boegel** [comment]
@robqiao The `GNU_SOURCE` template was broken for a while, was fixed recently (in EasyBuild v3.3.0), see https://github.com/easybuilders/easybuild-framework/pull/2235, maybe that explains it?
