### ISSUE TITLE
Script 'rpath_args.py' not found 

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-framework#2247]
After installing easybuild 3.3.0 inside a docker container using `pip install EasyBuild` I get this error when testing the --rpath support

```Script 'rpath_args.py' not found at expected location: /usr/lib/python2.7/site-packages/easybuild/scripts/rpath_args.py```

I have seen that pip installs this script in `/usr/easybuild/scripts/rpath_args.py`

**Comment by boegel** [comment]
@pescobar please check whether the changes to `find_eb_script` in #2249 fix this problem

**Comment by boegel** [comment]
fixed in #2249
