### ISSUE TITLE
avoid collisions when downloading source files

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#455]
We need a proper way to handle software packages that feature non-versioned source files (e.g. `mytool.tar.gz`).

**Comment by pneerincx** [comment]
Just ran into this issue today with Picard. Older versions had a version number in the downloaded file, but it's distributed as of version 2.5.0 without version number :(. Combined with a lack of a checksum for the sources (checksums are optional :o) this resulted in an easyconfig for version 2.9.x that happily found a previously downloaded version 2.7.x and installed that as 2.9.x: oops. Robust handling of unversioned sources would be welcome and related I wouldn't mind if checksum become mandatory for easyconfigs ;)...

**Comment by boegel** [comment]
@pneerincx Making checksums mandatory is something we're considering, but it'll be quite an effort.

Also, even though it would have helped to avoid this problem occurring silently, it's still a good idea to rename sources that are not versioned. This is something we should also support in EasyBuild, maybe with a syntax like:

```python
sources = ['picard.zip:picard-%(version)s.zip']
```

EasyBuild would then first go looking for `picard-%(version)s.zip`, and only download when it's missing.

Of course, this should be accompanied with a checksum to avoid downloading and renaming the wrong zip file...

**Comment by boegel** [comment]
follow up in #2223 which adds support for renaming sources on download
