### ISSUE TITLE
Add toolchain support for PGI compilers 

### ISSUE THREAD

**Issue by ajdecon** [hpcugent/easybuild-framework#554]
The [Portland Group's](http://www.pgroup.com/) compilers are popular at a lot of HPC sites, especially those making use of accelerators. My site in particular (NVIDIA) makes heavy use of the PGI compilers, as do a lot of the sites I've worked with in the past. These compilers also provide some uncommon and/or unique capabilities such as CUDA Fortran and OpenACC, so I think it makes sense to have toolchain support in EasyBuild.

I'm playing with this a bit myself, but I'm both time-constrained (lots of projects in-flight, and I'm a lone-gun sysadmin); and also lawyer-constrained (code contributions must go through legal before I get to submit a pull request). So I thought I'd open an issue to see if others are working on this, or interested in seeing this support. :)

Simple support should not be too difficult to add, but I would guess additional work to do things like make support for OpenACC builds work in a simple/easy way,

While it's slow and cumbersome for me to contribute code directly, I can provide less direct support in terms of answering questions, testing others' code, and providing limited access to a cluster which has the PGI compilers. ( @boegel and @JensTimmerman already have accounts, and I can potentially add two or three others if you're specifically working on EasyBuild.)

**Comment by rjeschmi** [comment]
Can we close this since it is handled in more productive PRs like #1342 ?

**Comment by boegel** [comment]
+1 @rjeschmi, let's follow up in #1342, or maybe better, in https://github.com/hpcugent/easybuild/issues/211
