### ISSUE TITLE
Intel based Tool Chains need to have GCC as Compile Time Dependency

### ISSUE THREAD

**Issue by pforai** [hpcugent/easybuild-framework#635]
The Intel based tool chains (ICTCE et al) have a dependency on GCC (mostly it seems to be G++) as a dependency during the configuration of quite a lot of builds. Didn't have time yet to get into more in-depth details, but it seems to me that it's mostly ifort that wants g++ visible in $PATH. 

It would be very good to have that reflected in the ICTCE based modules or in the tool chain definitions themselves. Be aware that having GCC present somewhere during configuration is a potential wormhole for probably many configuration issues and intuitively could lead to a lot of (maybe hidden) problems. 

On our end of things we deal with this issue by loading the GCC module before we compile things with ICTCE as Lmod (our environment modules implementation) doesn't purge all the modules before EB runs, so in most cases we are good with the result.

**Comment by boegel** [comment]
the `intel` toolchain effectively includes GCC as a component, so closing this
