### ISSUE TITLE
binutils should be part of compiler toolchains

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#644]
`binutils`, that provides tools like `ld` and `ar`, should be part of (all) compilers toolchains.

So would solve a number of problems, e.g.:

* #108, i.e. `zlib` being a dependency for `ar`, and problems that arise when `zlib` is also a dependency somewhere in the software dependency tree
* https://github.com/hpcugent/easybuild-easyconfigs/pull/217: MariaDB requires a GCC that was built against a recent `binutils`
* https://github.com/hpcugent/easybuild-easyconfigs/issues/274: move common dependencies to the toolchains would be a significant cleanup

It would also make the list of dependencies cleaner for various software packages, that now explicitly need to list `zlib` as a dependency.

Other likely candidates to be included in all compiler toolchains include:
* `ncurses`

**Comment by wpoely86** [comment]
A first try: hpcugent/easybuild-easyconfigs#1346

**Comment by boegel** [comment]
binutils will be included as a dependency in the 2015b 'common' toolchains, see https://github.com/hpcugent/easybuild-easyconfigs/pull/1695 and https://github.com/hpcugent/easybuild-easyconfigs/pull/1696
