### ISSUE TITLE
offer a warning if environment modules versions is <3.2.10

### ISSUE THREAD

**Issue by fgeorgatos** [hpcugent/easybuild-framework#689]
since easybuild is robust enough to build super-complex modules and highlight the frequence of the cache-pointers-corruption bug, it would be ideal that people get a clear warning with a 3-second pause (or something of that type) if they run under the buggy version of environment modules; this will ensure that EB will not be mis-considered as buggy and issue reports with dialog output will contain all the important info.

**Comment by boegel** [comment]
fixed in #963
