### ISSUE TITLE
use dicts for dependency specification, instead of tuples.

### ISSUE THREAD

**Issue by JensTimmerman** [hpcugent/easybuild-framework#691]
Named parameters are a bit better to understand then the current tuples with  2 optional components, of which the 3rd can be either bool or tuple/list.

I'm not sure if we should do away with the tuples, because they are convenient for the most common case (name, version).
 But maybe we should then deprecate tuples with more then 2 entries? (discussion needed, )

**Comment by boegel** [comment]
`_parse_dependency` includes support for specifying a dep in `dict` format (even for `.eb` easyconfigs in "format v1");

the experimental `.yeb` easyconfig format cleaner support for specifying deps, in dict-like syntax in YAML (see #1479)

so, this can be closed imho
