### ISSUE TITLE
also try and resolve dependencies using subtoolchains

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#741]
Feature proposal by @berndmohr:

For resolving dependencies specified in a `goolf` toolchain build, we could also try and resolve them using a `gompi` toolchain and maybe even a `GCC` toolchain.

This would allow that tools like `CMake` are built with a minimal toolchain (e.g. `CMake-2.8.4-GCC-4.7.2`), and still can be used in a `goolf` easyconfig as build dependency.

This is less strict than what is being done now (i.e. only use the specified toolchain, either the one in `toolchain` or in the custom toolchain in the dependency specification).

I'm confident @besserox would support this feature proposal too, let's see what @stdweird thinks about it. :-)

**Comment by ocaisa** [comment]
I struggle to see how you can get this to work without having some kind of equivalency classes defined between toolchains (somewhat like what Fotis was describing but not so fine-grained) and well defined inheritance in a toolchain (gmpolf inherits gompi inherits GCC) so that searching back down the toolchain hierarchy is straightforward. 

Not to worry, this is what I plan to work on next week (along with a new HMNS that would leverage hierarchically defined toolchains)!

**Comment by boegel** [comment]
@ocaisa: that's indeed indispensable, but it could be as simple as adding something like this in the toolchain definitions that are now already in the framework:

```python
# in goolf
subtoolchains = ['gompi', 'GCC']
```

`dummy` would then be an implied subtoolchains for all others

**Comment by ocaisa** [comment]
That might be enough...but then which version of gompi matches the current toolchain? If it's not listed somehow in the easyconfig, wouldn't it be a struggle to figure out uniquely?

**Comment by boegel** [comment]
The versioning can be tricky, yes. But we can do that best effort...

For several toolchains (e.g. `goolf`), subtoolchains (e.g. `gompi`) that are *not* individual toolchain components (e.g. `GCC`) have the same version as their parent toolchain.

So, if a subtoolchain is included as an actual toolchain component, use the component version, if not, use the toolchain version itself.

For example, when using `goolf/1.4.10`, consider `gompi/1.4.10` (use toolchain version), and `GCC/4.7.2` (use `GCC` component version), and eventually also `dummy`.

That way, several toolchains we're using already will work with this procedure, and others can be made compatible with this in future versions of the toolchain.

**Comment by boegel** [comment]
@ocaisa: fixed with #1306?

**Comment by ocaisa** [comment]
Yes, I think so
