### ISSUE TITLE
bootstrap harmless error message

### ISSUE THREAD

**Issue by stdweird** [hpcugent/easybuild-framework#857]
reported by markus geimer. bootstrap exists with
```
Exception TypeError: "'NoneType' object is not callable" in <function
_removeHandlerRef at 0x2ec7500> ignored
```

seems like fancylogger is not cleaning up properly?

**Comment by boegel** [comment]
@geimer: is this still a problem?

**Comment by geimer** [comment]
@boegel: Seems to be gone.  I did a quick test with the latest bootstrap script and didn't see this message anymore.

**Comment by boegel** [comment]
@geimer OK, thanks for the info, closing this then.
