### ISSUE TITLE
Extensions using the same buildopts than main program

### ISSUE THREAD

**Issue by hajgato** [hpcugent/easybuild-framework#991]
The extensions using the same buildopts than the main program. For extensions, we have to have the possibility to define separate buildopts, prebuilopts, and so on.

**Comment by pescobar** [comment]
maybe related: https://github.com/hpcugent/easybuild-easyblocks/issues/587

**Comment by verdurin** [comment]
Relevant mentions on IRC:

http://pastebin.com/EdYhRQQg

https://gist.github.com/chrisacbr/eed6b26bc49576c3b2707cf61a08c91d

**Comment by gatagat** [comment]
I am new to eb, but I was surprised to see that the extensions are not handled just as normal main programs. I mean having a separate eb file for each extension and being able to include any eb as extension. That would provide all the options available for normal eb files out of the box.

**Comment by boegel** [comment]
Support for specifying custom easyconfig parameters per extension is added with #2194, which should close this issue.

@gatagat The concept of extensions was introduced exactly to avoid having a separate easyconfig file per extension. Later on, we also added support for installing extensions like `numpy` as stand-alone modules, where you indeed need a separate easyconfig file.

**Comment by boegel** [comment]
#2194 is merged so support for specifying `buildopts` and other easyconfig parameters will be included in the upcoming EasyBuild v3.2.0
